Repository lucee/Lucee, pull requests merged in 2021-06, with the labels that each got.

#943 cffile: inconsistent behavior of the attribute nameConflict with "makeunique" value LDEV-2872
  core/src/main/java/lucee/runtime/tag/FileTag.java
  test/tickets/LDEV2872.cfc
Labels: bugfix

#1349 show current timezones on server.regional in admin
  core/src/main/cfml/context/admin/server.regional.cfm
Labels: enhancement

#1355 add GitHub Action to build lucee LDEV-3555
  .github/workflows/main.yml
Labels: build

#1356 add GitHub Action to build lucee LDEV-3555
  .github/workflows/main.yml
Labels: build

#1358 refactor more test code into cfm files
  ant/run-testcases.xml
  test/bootstrap-tests.cfm
  test/run-tests.cfm
Labels: build, testcase

#1360 report if jar and lco files exist
  .github/workflows/main.yml
  ant/upload-to-s3.xml
Labels: build

#1363 fix docker image builds for new travis repo (5.3)
  travis-docker-build.sh
Labels: build

#1362 fix docker image builds for new travis repo (6.0)
  travis-docker-build.sh
Labels: build

#1365 renable zip tests
  test/tags/Zip.cfc
Labels: testcase

#1366 enable a subset of the mysql driver version tests
  test/datasource/MySQL_Driver.cfc
Labels: testcase
