Repository lucee/Lucee, pull requests merged in 2021-11, with the labels that each got.

#1448 Added a fix for array.Set() to show correct error message in LDEV-3732
  core/src/main/java/lucee/runtime/functions/arrays/ArraySet.java
Labels: bugfix

#1451 LDEV 3742 - CFContent delivers wrong Content-Type
  core/src/main/java/lucee/runtime/tag/Content.java
Labels: bugfix

#1447 Added a function ArrayRemoveDuplicates for LDEV-442
  core/src/main/java/lucee/runtime/functions/arrays/ArrayRemoveDuplicates.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/ArrayRemoveDuplicates.cfc
  test/tickets/LDEV3167.cfc
Labels: enhancement, testcase

#1443 performance: Change Math.rand() to ThreadLocalRandom
  core/src/main/java/lucee/commons/collection/Hashing.java
  core/src/main/java/lucee/commons/img/AbstractCaptcha.java
  core/src/main/java/lucee/commons/lang/NumberUtil.java
  core/src/main/java/lucee/runtime/net/ntp/NtpMessage.java
  core/src/main/java/lucee/transformer/cfml/evaluator/impl/Cache.java
  core/src/main/java/lucee/transformer/cfml/evaluator/impl/Lock.java
Labels: enhancement

#1426 Added a new function queryIsEmpty() for LDEV-401
  core/src/main/java/lucee/runtime/functions/query/QueryIsEmpty.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/QueryIsEmpty.cfc
Labels: enhancement, testcase

#1419 add cfinputclassic encodeValue=false
  core/src/main/java/lucee/runtime/tag/Input.java
  core/src/main/java/resource/tld/core-base.tld
Labels: enhancement

#1406 extend thread cookie tests LDEV-2308
  ant/run-testcases.xml
  test/tickets/LDEV2308.cfc
  test/tickets/LDEV2308/no-cookies/Application.cfc
  test/tickets/LDEV2308/no-session/Application.cfc
Labels: testcase

#1270 len() tests for arrays, structs & query objects
  test/jira/Jira2998.cfc
Labels: testcase

#1260 testcase for serializeJSON() with different query column types LDEV-3406
  test/tickets/LDEV3406.cfc
Labels: testcase

#1117 Added a testcase with H2 datasource for LDEV-2902
  test/tickets/LDEV_2902.cfc
  test/tickets/LDEV_2902/Application.cfc
  test/tickets/LDEV_2902/test.cfm
Labels: testcase

#1154 test for binaryDecode() and toBinary() are decoding invalid base64 date LDEV-3034
  test/tickets/LDEV3034.cfc
Labels: testcase

#1140 test for cfswitch allow duplicated case LDEV-3197
  test/tickets/LDEV3197.cfc
Labels: testcase

#1221 Added a testcase with circular reference for LDEV-3333
  test/tickets/LDEV3333.cfc
Labels: testcase

#1120 Added a test case for directoryList() - listinfo with name LDEV-3188
  test/tickets/LDEV_2152.cfc
Labels: testcase

#1227 testcase to check cfhttp url with queryString LDEV-3349
  test/tickets/LDEV3349.cfc
  test/tickets/LDEV3349/test.cfm
Labels: testcase

#1339 Added StringEach and test LDEV-3181
  core/src/main/java/lucee/runtime/functions/string/StringEach.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/StringEach.cfc
Labels: enhancement, testcase

#1338 Added StringEvery and test LDEV-3180
  core/src/main/java/lucee/runtime/functions/arrays/ArrayEvery.java
  core/src/main/java/lucee/runtime/functions/closure/Every.java
  core/src/main/java/lucee/runtime/functions/query/QueryEvery.java
  core/src/main/java/lucee/runtime/functions/string/StringEvery.java
  core/src/main/java/lucee/runtime/functions/struct/StructEvery.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/StringEvery.cfc
Labels: enhancement, testcase

#1337 Added StringFilter and test LDEV-3179
  core/src/main/java/lucee/runtime/functions/arrays/ArrayFilter.java
  core/src/main/java/lucee/runtime/functions/closure/Filter.java
  core/src/main/java/lucee/runtime/functions/query/QueryFilter.java
  core/src/main/java/lucee/runtime/functions/string/StringFilter.java
  core/src/main/java/lucee/runtime/functions/struct/StructFilter.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/StringFilter.cfc
Labels: enhancement, testcase

#1336 Added StringMap and test LDEV-3178
  core/src/main/java/lucee/runtime/functions/arrays/ArrayMap.java
  core/src/main/java/lucee/runtime/functions/closure/Map.java
  core/src/main/java/lucee/runtime/functions/query/QueryMap.java
  core/src/main/java/lucee/runtime/functions/string/StringMap.java
  core/src/main/java/lucee/runtime/functions/struct/StructMap.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/StringMap.cfc
Labels: enhancement, testcase

#1256 improve mailserver testcase LDEV-1868
  test/tickets/LDEV_1868.cfc
Labels: testcase

#1237 testcase for expandPath mapping case insensitive filename LDEV-3369
  test/tickets/LDEV3369.cfc
Labels: testcase

#1236 testcase, lucee XML document XmlRoot has its own XmRoot LDEV-3353
  test/tickets/LDEV3353.cfc
Labels: testcase

#1232 testcase for SMALLINT with signed and unsigned datatype LDEV-3358
  test/tickets/LDEV3358.cfc
  test/tickets/LDEV3358/Application.cfc
  test/tickets/LDEV3358/test.cfm
Labels: testcase

#1222 Added a testcase to check size of component with accessors for LDEV-3335
  test/tickets/LDEV3335.cfc
  test/tickets/LDEV3335/test.cfm
  test/tickets/LDEV3335/testMannual.cfc
  test/tickets/LDEV3335/testNoAccessors.cfc
  test/tickets/LDEV3335/testWithAccessors.cfc
Labels: testcase

#1220 Added a testcase for custom tag caller
  test/tickets/LDEV3309.cfc
  test/tickets/LDEV3309/cusTag.cfm
  test/tickets/LDEV3309/test.cfm
Labels: testcase

#1248 testcase for xmlTransform() with XSL files LDEV-3387
  test/tickets/LDEV3387.cfc
  test/tickets/LDEV3387/xml-to-json.xsl
  test/tickets/LDEV3387/xml-xsl.xsl
Labels: testcase

#1219 add imageResize tests for blurfactor and interpolation LDEV-2102
  test/functions/ImageResize.cfc
Labels: testcase

#1159 Added a test case for array functions that are use struct values
  test/functions/arrayFunctions.cfc
Labels: testcase

#1158 testcase for CFScript Parser confused by <cfcomponent> string LDEV-3228
  test/tickets/LDEV3228.cfc
  test/tickets/LDEV3228/commentComp.cfc
  test/tickets/LDEV3228/mixedComp.cfc
  test/tickets/LDEV3228/scriptComp.cfc
  test/tickets/LDEV3228/scriptCompTwo.cfc
  test/tickets/LDEV3228/tagComp.cfc
Labels: testcase

#1216 Added a testcase to check undefined array element for LDEV-3319
  test/tickets/LDEV3319.cfc
Labels: testcase

#1243 Added a testcase: dateDiff member function with dateTimeFormat string
  test/tickets/LDEV3384.cfc
Labels: testcase

#1155 test for Copy restricted PDF merge, "PdfReader not opened with owner password" LDEV-3215
  test/tickets/LDEV3215.cfc
  test/tickets/LDEV3215/sample.pdf
  test/tickets/LDEV3215/sample2.pdf
Labels: testcase

#1152 test for Empty valuecfqueryparam type="list" with SQL IN operator fails LDEV-3207
  test/tickets/LDEV3207.cfc
  test/tickets/LDEV3207/Application.cfc
  test/tickets/LDEV3207/LDEV3207.cfm
Labels: testcase

#630 test case for Recursive directoryList Sort is Depth First instead of Breadth First LDEV-2152
  test/tickets/LDEV2152.cfc
Labels: testcase

#1249 testcase for cfpdf action=merge LDEV-3391
  test/tickets/LDEV3391.cfc
Labels: testcase

#1261 add build test for LUCEE_ENABLE_WARMUP
  ant/build-core.xml
  ant/build-warmup-test.xml
Labels: testcase, build

#1162 listLen() with "includeEmptyFields" argument is 0 for empty string LDEV-3253
  core/src/main/java/lucee/runtime/type/util/ListUtil.java
  test/functions/listLen.cfc
Labels: testcase, bugfix

#829 fix isValid('integer', 'Yes') returns true LDEV-2642
  core/src/main/java/lucee/runtime/op/Decision.java
  test/tickets/LDEV2642.cfc
Labels: testcase, bugfix

#875 replaceList() doesn't handle optional args the same as Adobe CF LDEV-2729
  core/src/main/java/lucee/runtime/functions/string/ReplaceList.java
  test/tickets/LDEV2729.cfc
Labels: testcase, bugfix

#595 Diff member function for dateDiff incompatible with ACF LDEV-2044
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV2044.cfc
Labels: testcase, bugfix

#863 Listfind & Listfindnocase works incorrectly while using includeEmptyFields=true LDEV-2710
  core/src/main/java/lucee/runtime/type/util/ListUtil.java
  test/tickets/LDEV2710.cfc
Labels: testcase, bugfix

#1477 Made a corrections in testcase to image.paste() with named arguments for LDEV-3082
  test/tickets/LDEV3082.cfc
  test/tickets/LDEV3082/test.cfm
Labels: testcase

#1437 LDEV-3721 cookie encode
  ant/run-testcases.xml
  core/src/main/java/lucee/runtime/type/scope/CookieImpl.java
  test/tags/cookie.cfc
  test/tags/cookie/encode.cfm
Labels: testcase, bugfix

#1123 connectionLimit is not set to default (-1) via AdminAPI LDEV-1445
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
  test/tickets/LDEV_1445.cfc
Labels: testcase, bugfix, Conflict / Review

#1478 fix LDEV3496
  core/src/main/java/lucee/transformer/bytecode/expression/var/VariableImpl.java
  test/tickets/LDEV3496.cfc
Labels: bugfix

#1468 LDEV-3757 make cfexcute closing tag optional
  core/src/main/java/resource/tld/core-base.tld
  test/tags/Execute.cfc
Labels: enhancement, testcase

#1466 LDEV-1925 Support UUID and Inet DB types in OtherCast
  core/src/main/java/lucee/runtime/query/caster/OtherCast.java
Labels: enhancement
