Repository lucee/Lucee, pull requests merged in 2021-12, with the labels that each got.

#1469 LDEV-3617 test cases for internalRequest
  test/functions/InternalRequest.cfc
  test/functions/internalRequest/abort.cfm
  test/functions/internalRequest/cfcontent-file.cfm
  test/functions/internalRequest/cfcontent.cfm
  test/functions/internalRequest/echo.cfm
Labels: testcase

#1432 Added a fix to deserializeJSON() throw error for empty String in LDEV-3413
  core/src/main/java/lucee/runtime/functions/conversion/DeserializeJSON.java
Labels: bugfix

#1421 Added a fix to add the ESAPI/Compress extension in not installed list correctly.
  core/src/main/cfml/context/admin/ext.applications.list.cfm
Labels: bugfix

#1424 Added a fix to create task ID should checks both open and closed IDs for LDEV-3702
  core/src/main/java/lucee/runtime/spooler/SpoolerEngineImpl.java
Labels: bugfix

#1409 Added a testcase passby=value with script arguments
  test/tickets/LDEV3668.cfc
Labels: testcase

#1350 Added a fix for regression CFHTTP with multipart quoted boundary in LDEV-3545.
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: bugfix

#1482 Updated a testcase to use serializeJSON(), deserializeJSON() & toString() with circularly-referenced array for LDEV-3333
  test/tickets/LDEV3333.cfc
Labels: testcase

#1504 LDEV-3793 update postgres extension to 42.2.20
  core/src/main/java/META-INF/MANIFEST.MF
  core/src/main/java/lucee/runtime/db/DBUtil.java
  test/_setupTestServices.cfc
  test/datasource/PostgreSQL.cfc
  test/jira/Jira2903.cfc
  test/tickets/LDEV2566/postgreSQL/Application.cfc
Labels: enhancement
