Repository lucee/Lucee, pull requests merged in 2021-04, with the labels that each got.

#1255 Log native QoQ exceptions as a debug exception LDEV-3400
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/exp/DatabaseException.java
  core/src/main/java/lucee/runtime/type/QueryColumnRef.java
  core/src/main/java/lucee/runtime/type/QueryImpl.java
Labels: enhancement

#1241 fix cgi scope in debugging LDEV-3382
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/java/resource/context/admin/debug/Classic.cfc
  core/src/main/java/resource/context/admin/debug/Comment.cfc
  core/src/main/java/resource/context/admin/debug/Modern.cfc
  core/src/main/java/resource/context/admin/debug/Simple.cfc
Labels: bugfix, enhancement

#1139 can't configure a mapping to archive with primary as archive via the admin LDEV-2361
  core/src/main/cfml/context/admin/resources.mappings.edit.cfm
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: bugfix

#949 improve invalid datasource name exception LDEV-2887
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix, exceptions

#919 bugfix: can't delete a rest mapping LDEV-2816
  core/src/main/cfml/context/admin/resources.rest.cfm
Labels: bugfix

#906 extensions, clicking install with selecting a version, shows please wait LDEV-2797
  core/src/main/cfml/context/admin/ext.applications.detail.cfm
Labels: bugfix

#890 key [STRBASECOMPONENTTEMPLATE] doesn't exist in admin action=server.general LDEV-2752
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/server.general.cfm
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: bugfix

#868 fix Error -with the 'Debugging - Settings' in WEB Admin LDEV-2726
  core/src/main/cfml/context/admin/debugging.settings.cfm
Labels: bugfix

#847 admin assumes the local documentation extension is installed LDEV-2695
  core/src/main/cfml/context/admin/overview.cfm
  core/src/main/cfml/context/admin/resources/language/en.xml
Labels: bugfix

#912 truncate long string when throwing a json parsing error LDEV-2812
  core/src/main/java/lucee/runtime/interpreter/CFMLExpressionInterpreter.java
Labels: bugfix, exceptions

#825 fix admin button display LDEV-2633
  core/src/main/cfml/context/admin/debugging.templates.list.cfm
  core/src/main/cfml/context/admin/ext.providers.cfm
  core/src/main/cfml/context/admin/info.bundle.list.cfm
  core/src/main/cfml/context/admin/resources.cfx_tags.cfm
  core/src/main/cfml/context/admin/resources.customtags.list.cfm
  core/src/main/cfml/context/admin/resources.mappings.list.cfm
  core/src/main/cfml/context/admin/resources.rest.cfm
  core/src/main/cfml/context/admin/server.logging.list.cfm
  core/src/main/cfml/context/admin/services.cache.list.cfm
  core/src/main/cfml/context/admin/services.datasource.list.cfm
  core/src/main/cfml/context/admin/services.mail.serverlist.cfm
  core/src/main/cfml/context/admin/services.schedule.list.cfm
  core/src/main/cfml/context/admin/services.tasks.cfm
  core/src/main/cfml/context/res/js/admin.js
Labels: bugfix

#828 trim column names with QueryNew() LDEV-2637
  core/src/main/java/lucee/runtime/functions/query/QuerySetCell.java
  test/tickets/LDEV2637.cfc
Labels: bugfix, testcase

#790 fix invalid JSON as being treated as valid LDEV-1503
  core/src/main/java/lucee/runtime/interpreter/CFMLExpressionInterpreter.java
Labels: bugfix

#685 cfinput unimplemented attributes need to be flagged LDEV-2281
  core/src/main/java/lucee/runtime/tag/Input.java
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix, documentation

#739 sql debug output shows empty numeric values cast to null as [datatype] LDEV-1532
  core/src/main/java/lucee/runtime/tag/QueryParam.java
Labels: bugfix

#1175 show the correct webcharset value in admin for LDEV-3224
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#1148 allow specifying a file extension for getTempFile LDEV-2331
  core/src/main/java/lucee/runtime/functions/system/GetTempFile.java
  core/src/main/java/resource/fld/core-base.fld
Labels: enhancement

#1168 Added a fix to many arguments error in member function for LDEV-3244
  core/src/main/java/lucee/runtime/type/util/MemberUtil.java
Labels: exceptions

#1150 Added a correction in error message to directory delete for LDEV-3191
  core/src/main/java/lucee/runtime/tag/Directory.java
Labels: exceptions

#951 improve cffile action="read" exception LDEV-678
  core/src/main/java/lucee/runtime/tag/FileTag.java
Labels: exceptions

#1198 always use / for zip,tar,tgz resources LDEV-3285
  core/src/main/java/lucee/commons/io/res/type/tar/TarResourceProvider.java
  core/src/main/java/lucee/commons/io/res/type/tgz/TGZResourceProvider.java
  core/src/main/java/lucee/commons/io/res/type/zip/ZipResourceProvider.java
Labels: enhancement

#1184 Added a fix to admin mailserver update for LDEV-3231
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1164 Added a fix for delete non-existing schedule task in LDEV-3243
  core/src/main/java/lucee/runtime/tag/Schedule.java
Labels: bugfix

#1165 ArrayToStruct add valueAsKey LDEV-3171
  core/src/main/java/lucee/runtime/functions/arrays/ArrayToStruct.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/ArrayToStruct.cfc
Labels: enhancement

#1125 return debug logs as json via url param
  core/src/main/cfml/context/admin/debugging.logs.cfm
  core/src/main/cfml/context/admin/debugging.logs.detail.cfm
Labels: enhancement

#725 Delete mapping doesn't clear the .lar file LDEV-2379
  core/src/main/cfml/context/admin/resources.mappings.cfm
Labels: bugfix

#753 show the total number of implicit scope problems on the admin debug log list LDEV-2368
  core/src/main/cfml/context/admin/debugging.logs.cfm
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
Labels: enhancement

#1245 debugging bypass minimal execution time LDEV-3385
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/java/resource/context/admin/debug/Modern.cfc
Labels: enhancement

#1264 correct defaultcase tag description
  core/src/main/java/resource/tld/core-base.tld
Labels: documentation

#1233 added "epochms" and "epoch" masks to DateTimeFormat
  core/src/main/java/lucee/runtime/functions/displayFormatting/DateTimeFormat.java
  core/src/main/java/resource/fld/core-cfml.fld
Labels: Conflict / Review, enhancement

#1176 improve the error message for mixed arguments LDEV-3238
  core/src/main/java/lucee/transformer/bytecode/expression/var/VariableImpl.java
Labels: Conflict / Review, exceptions

#1272 change cflocation addToken to default to false LDEV-3437
  core/src/main/java/lucee/runtime/tag/Location.java
  core/src/main/java/resource/library/function/location.cfm
  core/src/main/java/resource/tld/core-base.tld
Labels: documentation, enhancement

#1273 pass in missing log for session datasource logging LDEV-3084
  core/src/main/java/lucee/runtime/type/scope/storage/IKStorageScopeSupport.java
Labels: bugfix

#1274 scope logging, change sql to debug, simple to info LDEV-3084
  core/src/main/java/lucee/runtime/type/scope/ScopeContext.java
  core/src/main/java/lucee/runtime/type/scope/storage/IKHandlerCache.java
  core/src/main/java/lucee/runtime/type/scope/storage/IKHandlerDatasource.java
  core/src/main/java/lucee/runtime/type/scope/storage/IKStorageScopeSupport.java
  core/src/main/java/lucee/runtime/type/scope/storage/StorageScopeCache.java
  core/src/main/java/lucee/runtime/type/scope/storage/StorageScopeDatasource.java
  core/src/main/java/lucee/runtime/type/scope/storage/db/Ansi92.java
Labels: enhancement

#1276 Added a fix to import password.txt even if hspw="" for LDEV-3439
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
Labels: bugfix

#1266 Improve the checking order for member functions LDEV-3428
  core/src/main/java/lucee/runtime/util/VariableUtilImpl.java
Labels: enhancement

#1279 fix typo
  core/src/main/cfml/context/admin/resources/language/de.xml
Labels: bugfix

#1095 Fixed issue where MSSQL driver is not matching JTDS results LDEV-3102
  core/src/main/java/lucee/runtime/type/QueryImpl.java
  test/tickets/LDEV3102.cfc
Labels: bugfix, testcase

#1282 fix LDEV-3103, use LF instead of CRLF encoding
  test/tickets/LDEV3103.cfc
Labels: bugfix, testcase

#1281 CFHTTP using TLS v1.3 (allows TLS 1.2 fallback) LDEV-3239
  core/src/main/java/lucee/runtime/tag/Http.java
  test/tags/Http.cfc
Labels: enhancement

#1096 Fix exceptions not being raised when using the MSSQL driver LDEV-3127
  core/src/main/java/lucee/runtime/type/QueryImpl.java
  test/tickets/LDEV3127.cfc
Labels: bugfix, testcase

#1284 add statusCode and contentType to debugging LDEV-3456
  core/src/main/java/lucee/runtime/debug/DebuggerImpl.java
Labels: enhancement

#1287 Update plugin.cfm
  core/src/main/cfml/context/admin/plugin.cfm
Labels: bugfix

#1285 Enhancement: Fix to return new directory name instead of null/void for DirectoryRename().
  core/src/main/java/lucee/runtime/functions/file/DirectoryRename.java
  core/src/main/java/lucee/runtime/tag/Directory.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/DirectoryRename.cfc
Labels: enhancement

#1292 Added a small correction for LDEV-2695
  core/src/main/cfml/context/admin/overview.cfm
Labels: bugfix

#1298 update description for scriptProtect
  core/src/main/java/resource/tld/core-cfml.tld
Labels: documentation

#1301 Removed the caught check and updated the debugging language to be exceptions LDEV-3165
  core/src/main/java/lucee/runtime/PageContextImpl.java
  core/src/main/java/resource/context/admin/debug/Classic.cfc
  core/src/main/java/resource/context/admin/debug/Comment.cfc
  core/src/main/java/resource/context/admin/debug/Modern.cfc
  core/src/main/java/resource/context/admin/debug/Simple.cfc
Labels: enhancement

#1300 FIleAppend supports now file objects - Ldev 3424
  core/src/main/java/lucee/runtime/functions/file/FileAppend.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/FileAppend.cfc
Labels: enhancement, testcase

#1293 Added a Fix to retrieve the extension dropdown back in LDEV-3468
  core/src/main/cfml/context/admin/ext.applications.detail.cfm
Labels: bugfix

#1296 support custom struct for additional args for updateDatasource() in Administrator.cfc
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
Labels: enhancement

#1113 add stringSort LDEV-3153
  core/src/main/java/lucee/runtime/functions/string/StringSort.java
  core/src/main/java/resource/fld/core-base.fld
Labels: enhancement
