Repository lucee/Lucee, pull requests merged in 2021-05, with the labels that each got.

#1297 fix admin update process LDEV-3386
  core/src/main/cfml/context/admin/changeto.cfm
  core/src/main/cfml/context/admin/services.update.cfm
  core/src/main/cfml/context/admin/web.cfm
Labels: bugfix

#1310 Sorted the struct returned by GetTagList and GetFunctionList LDEV-3446
  core/src/main/java/lucee/runtime/functions/other/GetFunctionList.java
  core/src/main/java/lucee/runtime/functions/other/GetTagList.java
Labels: documentation, enhancement

#1315 backport LUCEE_BUILD_ENV support to 5.3
  ant/run-testcases.xml
  test/_setupTestServices.cfc
Labels: build, testcase

#1312 Added hash as a member method for String LDEV-1297
  core/src/main/java/resource/fld/core-base.fld
  test/functions/hash.cfc
Labels: enhancement

#1317 add a check that method is defined for cfinvoke with a webservice LDEV-3493
  core/src/main/java/lucee/runtime/tag/Invoke.java
Labels: bugfix

#1322 Moved the testcases LDEV1882, LDEV2349, LDEV2410 to FileSetAttribute() testcase
  test/functions/FileSetAttribute.cfc
  test/tickets/LDEV1880.cfc
  test/tickets/LDEV1892.cfc
  test/tickets/LDEV2410.cfc
  test/tickets/_LDEV2349.cfc
Labels: testcase

#1324 route admin restart thru web.cfm LDEV-3497
  core/src/main/cfml/context/admin/Application.cfc
  core/src/main/cfml/context/admin/ext.applications.list.cfm
  core/src/main/cfml/context/admin/restart.cfm
  core/src/main/cfml/context/admin/services.restart.cfm
  core/src/main/cfml/context/admin/web.cfm
  loader/build.xml
  loader/pom.xml
Labels: bugfix

#1203 testcase for this vs variables cfc scope LDEV-3296
  test/tickets/LDEV3296.cfc
  test/tickets/LDEV3296/sample.cfc
Labels: testcase

#1320 refactor test filters
  ant/run-testcases.xml
  core/src/main/java/lucee/runtime/jsr223/ScriptEngineImpl.java
  test/_setupTestServices.cfc
  test/_testRunner.cfc
  test/tickets/LDEV0835/Base.cfc
  test/tickets/LDEV2005.cfc
Labels: build, testcase

#1329 Fix spelling and grammar
  core/src/main/java/lucee/runtime/type/scope/ClusterNotSupported.java
Labels: exceptions

#1328 Added a fix to queryEach UDF use row struct as ordered for LDEV-3510
  core/src/main/java/lucee/runtime/type/it/ForEachQueryIterator.java
  test/jira/Jira2970.cfc
  test/jira/Jira2971.cfc
  test/jira/Jira2973.cfc
  test/jira/Jira2974.cfc
  test/jira/Jira2979.cfc
Labels: enhancement

#1330 query returnType array should struct return row as an ordered struct LDEV-3511
  core/src/main/java/lucee/runtime/type/QueryImpl.java
  core/src/main/java/lucee/runtime/type/query/QueryArray.java
  core/src/main/java/lucee/runtime/type/query/QueryStruct.java
  test/tickets/LDEV3511.cfc
Labels: enhancement

#1277 CFTIMER add units, variable attributes LDEV-3419 LDEV-3250
  core/src/main/java/lucee/runtime/tag/Timer.java
  core/src/main/java/resource/tld/core-base.tld
  test/tags/Timer.cfc
Labels: enhancement

#1280 don't get a jsessionid for child threads LDEV-2954
  core/src/main/java/lucee/runtime/net/http/HttpServletRequestDummy.java
Labels: bugfix

#1250 improve DirectoryList listInfo="path" performance LDEV-3394
  core/src/main/java/lucee/runtime/tag/Directory.java
Labels: enhancement

#1234 fix cffile NPE and improve error message in LDEV-3364
  core/src/main/java/lucee/runtime/tag/FileTag.java
Labels: bugfix, exceptions

#1055 fix typo and removed variant argument in Argon2CheckHash function LDEV-2883
  core/src/main/java/lucee/runtime/functions/other/Argon2CheckHash.java
  core/src/main/java/resource/fld/core-base.fld
Labels: bugfix

#1333 Added a new function directoryInfo() and action info in cfdirectory for LDEV-3294
  core/src/main/java/lucee/runtime/tag/Directory.java
  core/src/main/java/lucee/runtime/tag/DirectoryInfo.java
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/tld/core-base.tld
  test/functions/DirectoryInfo.cfc
Labels: enhancement

#1182 add fileCreated property to GetFileInfo and cffile action=info
  core/src/main/java/lucee/runtime/functions/file/GetFileInfo.java
  core/src/main/java/lucee/runtime/tag/FileTag.java
  test/functions/GetFileInfo.cfc
Labels: enhancement

#1204 update testbox to 4.2.1
  ant/build-core.xml
Labels: build, testcase

#1346 ensure tests are run in a sorted order LDEV-3541
  test/_testRunner.cfc
Labels: build, testcase
