Repository lucee/Lucee, pull requests merged in 2021-02, with the labels that each got.

#1200 cache maven resources with travis-ci
  .travis.yml
Labels: build

#1208 image tests don't need to access external resources
  test/functions/ImageDrawArc.cfc
  test/functions/ImageDrawBeveledRect.cfc
  test/functions/imageClearRect.cfc
  test/functions/imageReadbase64.cfc
  test/tickets/LDEV2558.cfc
  test/tickets/_LDEV3024.cfc
Labels: testcase

#1187 format exception message
  core/src/main/java/lucee/runtime/exp/CatchBlockImpl.java
  core/src/main/java/lucee/runtime/exp/DatabaseException.java
  core/src/main/java/lucee/runtime/exp/FTPException.java
  core/src/main/java/lucee/runtime/exp/FunctionException.java
  core/src/main/java/lucee/runtime/exp/MissingIncludeException.java
  core/src/main/java/lucee/runtime/exp/RequestTimeoutException.java
  core/src/main/java/lucee/runtime/exp/TagAttributeException.java
  core/src/main/java/lucee/runtime/exp/TagNotSupported.java
  core/src/main/java/lucee/runtime/type/util/ComponentUtil.java
Labels: exceptions

#1199 fix cfexecute directory arg resource type check LDEV-3117
  core/src/main/java/lucee/commons/cli/Command.java
  test/tags/Execute.cfc
Labels: bugfix

#1172 spelling and grammar
  core/src/main/java/resource/fld/core-lucee.fld
Labels: documentation

#1160 improve execute grammar
  core/src/main/java/lucee/runtime/tag/Execute.java
Labels: exceptions

#1207 add QueryRenameColumn
  core/src/main/java/lucee/runtime/functions/query/QueryRenameColumn.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/QueryRenameColumn.cfc
  test/tags/Query.cfc
Labels: enhancement

#1206 verbiage updates
  core/src/main/java/lucee/runtime/type/QueryColumnImpl.java
Labels: exceptions

#1161 don't lowercase attribute names LDEV-3252
  core/src/main/java/lucee/runtime/functions/other/GetTagData.java
Labels: documentation

#1137 attributes - > arguments LDEV-3198
  core/src/main/java/lucee/transformer/cfml/expression/AbstrCFMLExprTransformer.java
Labels: exceptions

#1213 add logging of lucee start time in build
  ant/build-create-archive.xml
  ant/run-testcases.xml
Labels: build

#1210 remove the unwanted directory after testing in testcases
  test/tickets/LDEV0941.cfc
Labels: testcase
