Repository lucee/Lucee, pull requests merged in 2021-07, with the labels that each got.

#1367 improve FileSetAttribute tests
  test/functions/FileSetAttribute.cfc
Labels: testcase

#1369 add some orm events tests
  test/orm/Hibernate.cfc
  test/orm/events/Application.cfc
  test/orm/events/Code.cfc
  test/orm/events/eventHandler.cfc
  test/orm/events/index.cfm
Labels: testcase

#1371 add testbox junit reporting for GHA
  .github/workflows/main.yml
  .gitignore
  test/run-tests.cfm
Labels: testcase

#1377 classify extension release status based on all versions
  core/src/main/cfml/context/admin/ext.applications.list.cfm
Labels: bugfix

#833 test for CFZIP action="unzip" overwrite="true" deletes existing directories LDEV-2660
  test/tickets/LDEV2660.cfc
  test/tickets/LDEV2660/bundle.zip
  test/tickets/LDEV2660/index.cfm
Labels: testcase

#1382 add -DtestExtensions="ext dist dir" to build process
  ant/build-core.xml
  ant/build-utils.xml
  test/tickets/LDEV2660.cfc
Labels: build

#1383 test case for qoq union bug LDEV3615
  test/tickets/LDEV3615.cfc
Labels: testcase

#1119 Added iterations with nullSupport="true" for LDEV-1296
  test/tickets/LDEV_1296.cfc
Labels: testcase

#1385 add support for running additional tests (-DtestAdditional="dir")
  ant/build-core.xml
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: build

#1386 Add -DtestSkip="false" and -DtestDebug="true" build options
  ant/build-core.xml
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: build, testcase

#1387 Added a testcase to cfhtmlhead text attribute with body for LDEV-3618
  test/tickets/LDEV3618.cfc
  test/tickets/LDEV3618/test.cfm
Labels: testcase

#1388 test case directoryList sees directories as files LDEV-3614
  test/tickets/LDEV3614.cfc
Labels: testcase

#1390 add a test profile for custom s3 urls
  test/_setupTestServices.cfc
  test/extension/S3.cfc
Labels: build, testcase
