Repository lucee/Lucee, pull requests merged in 2021-03, with the labels that each got.

#1142 Added a fix for queryClear member function
  core/src/main/java/lucee/runtime/functions/query/QueryClear.java
  core/src/main/java/resource/fld/core-base.fld
Labels: bugfix

#1138 Added a fix to show function name in error message for LDEV-3198
  core/src/main/java/lucee/runtime/exp/FunctionException.java
Labels: exceptions

#1157 use forceunique for extension upload LDEV-3122
  core/src/main/cfml/context/admin/ext.applications.upload.cfm
Labels: admin, enhancement

#917 Extensions with no "release" update available are showing as requiring an update LDEV-2716
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#758 show lucee loader version on overview page LDEV-2459
  core/src/main/cfml/context/admin/overview.cfm
Labels: enhancement

#1173 Added a fix to show jar and patches path in admin update page and added new cfadmin action=getLoaderInfo
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/services.update.cfm
  core/src/main/java/lucee/runtime/tag/Admin.java
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: admin, enhancement

#1215 Added a PR to remove unwanted files from test in 6.0
  test/tickets/LDEV0941.cfc
Labels: testcase

#945 randomize filenames for file uploads LDEV-2877
  core/src/main/java/lucee/runtime/type/scope/FormImpl.java
Labels: enhancement

#1217 catch the error using try catch instead of throw in testcase LDEV-2410
  test/tickets/LDEV2410.cfc
Labels: testcase

#1180 show application name in log & set default value true for attribute application in cflog LDEV-3266
  core/src/main/java/lucee/runtime/tag/Log.java
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix

#1224 update cfc tags to use ordered, quoted attributes
  core/src/main/java/resource/library/tag/AjaxImport.cfc
  core/src/main/java/resource/library/tag/AjaxProxy.cfc
  core/src/main/java/resource/library/tag/Div.cfc
  core/src/main/java/resource/library/tag/Dump.cfc
  core/src/main/java/resource/library/tag/Layout.cfc
  core/src/main/java/resource/library/tag/LayoutArea.cfc
  core/src/main/java/resource/library/tag/Map.cfc
  core/src/main/java/resource/library/tag/MapItem.cfc
  core/src/main/java/resource/library/tag/MediaPlayer.cfc
  core/src/main/java/resource/library/tag/Window.cfc
Labels: documentation

#1218 improve testbox output
  ant/build-core.xml
  ant/run-testcases.xml
  test/tickets/LDEV1750.cfc
Labels: build, testcase

#1226 add tests calling all top level admin pages LDEV-3195
  ant/run-testcases.xml
  test/general/AdminPages.cfc
Labels: testcase

#1229 update datasource logging to mention storage
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/java/resource/context/admin/logging/appender/DatasourceAppender.cfc
  core/src/main/java/resource/context/admin/resources/language/de.xml
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: documentation

#1230 update datasource logging to mention storage
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/java/resource/context/admin/logging/appender/DatasourceAppender.cfc
  core/src/main/java/resource/context/admin/resources/language/de.xml
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: documentation

#1228 Fix loading of required bundles LDEV-3348
  ant/build-core.xml
  loader/pom.xml
Labels: bugfix, build

#1231 add a test case to check local docs
  test/general/localDocs.cfc
Labels: testcase

#1239 add a filter for dbinfo type="table" table="%"
  core/src/main/java/lucee/runtime/tag/DBInfo.java
  core/src/main/java/resource/tld/core-base.tld
Labels: enhancement

#1247 add auto deployLco option to build LDEV-3389
  ant/build-core.xml
Labels: build

#1258 Added a fix to improve the error message in LDEV-3404
  core/src/main/java/lucee/runtime/net/http/CertificateInstaller.java
Labels: exceptions

#1251 build - skip compiling testbox when in fast, add quick mode
  ant/build-bundles.xml
  ant/build-core.xml
  ant/build-create-archive.xml
  ant/build-extensions.xml
  ant/build-utils.xml
  ant/upload-to-s3.xml
  loader/build.xml
  loader/pom.xml
Labels: build

#1223 update getContextes to use renamed admin.getContexts
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
Labels: bugfix

#1244 add option to debug threads LDEV-3380
  core/src/main/cfml/context/admin/debugging.settings.cfm
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/java/lucee/runtime/PageContextImpl.java
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
  core/src/main/java/lucee/runtime/config/ConfigFactory.java
  core/src/main/java/lucee/runtime/config/ConfigPro.java
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  core/src/main/java/lucee/runtime/tag/Admin.java
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
  core/src/main/java/resource/context/admin/resources/language/de.xml
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: enhancement

#1259 fix thumbnail caching LDEV-3121
  core/src/main/cfml/context/admin/ext.functions.cfm
  core/src/main/cfml/context/admin/web_functions.cfm
Labels: bugfix

#1238 Added a fix to show extension update notification in overview page for LDEV-3350
  core/src/main/cfml/context/admin/update.cfm
Labels: bugfix

#851 scheduled tasks show the start time LDEV-2692
  core/src/main/cfml/context/admin/services.schedule.list.cfm
Labels: enhancement

#756 make release/pre release/snapshot buttons consistent LDEV-2462
  core/src/main/cfml/context/admin/ext.applications.list.cfm
Labels: enhancement
