Repository lucee/Lucee, pull requests merged in 2022-06, with the labels that each got.

#1651 Added a test to cflog without file attribute for LDEV-3978
  test/tickets/LDEV3978.cfc
  test/tickets/LDEV3978/LDEV3978.cfm
Labels: testcase

#1648 Added a testcase to isJson() with large exponent value in string for LDEV-4006
  test/tickets/LDEV4006.cfc
Labels: testcase

#1645 Added a testcase to onSessionEnd() with sessionRotate() for LDEV-3478
  test/tickets/LDEV3478.cfc
  test/tickets/LDEV3478/Jee_session_rotate/Application.cfc
  test/tickets/LDEV3478/Jee_session_rotate/test_jee_sessionEnd.cfm
  test/tickets/LDEV3478/cfml_session_rotate/Application.cfc
  test/tickets/LDEV3478/cfml_session_rotate/test_cfml_sessionEnd.cfm
Labels: testcase

#1646 Added a testcase to serialize the component object which has a java object in variable for LDEV-3997
  test/tickets/LDEV3997.cfc
  test/tickets/LDEV3997/test.cfc
Labels: testcase

#1610 Added a testcase to file locking issue in isImageFile() for LDEV-3931
  test/tickets/LDEV3931.cfc
Labels: testcase

#1411 Added a testcase to getComponentMetaData() with final CFC for LDEV-3584
  test/tickets/LDEV3584.cfc
  test/tickets/LDEV3584/test.cfc
Labels: testcase

#1399 Added a testcase to duplicate() with ORM object for LDEV-2862
  test/tickets/LDEV2862.cfc
  test/tickets/LDEV2862/Application.cfc
  test/tickets/LDEV2862/test.cfc
  test/tickets/LDEV2862/test.cfm
  test/tickets/LDEV2862/test2.cfc
Labels: testcase

#1624 Added a testcase to check the base64 value of image from ImageNew() for LDEV-3964
  test/tickets/LDEV3964.cfc
Labels: testcase

#1623 Added a testcase to using colon(:) in script syntax function attribute for LDEV-3963
  test/tickets/LDEV3963.cfc
  test/tickets/LDEV3963/LDEV3963.cfm
Labels: testcase

#1620 Added a testcase to comment in tag-in-script syntax for LDEV-3951
  test/tickets/LDEV3951.cfc
  test/tickets/LDEV3951/LDEV3951.cfm
Labels: testcase

#1599 Added a testcase to thread statement inside a lambda function for LDEV-3914
  test/tickets/LDEV3914.cfc
  test/tickets/LDEV3914/test.cfm
Labels: testcase

#1589 Added a testcase to accessing static.variable of the component for LDEV-3903
  test/tickets/LDEV3903.cfc
  test/tickets/LDEV3903/testComp.cfc
Labels: testcase

#1597 Added a testcase to check cfhttp with mimetype application/x-www-form-urlencoded for LDEV-3679
  test/tickets/LDEV3679.cfc
  test/tickets/LDEV3679/application-x-www-form-urlencoded-test
  test/tickets/LDEV3679/test.cfm
Labels: testcase

#1596 Added a testcase to check two different CFC has the importDefinition with the same path and name for LDEV-3912
  test/tickets/LDEV3912.cfc
  test/tickets/LDEV3912/app1/sub/importCFC.cfc
  test/tickets/LDEV3912/app1/testApp1.cfc
  test/tickets/LDEV3912/app2/sub/importCFC.cfc
  test/tickets/LDEV3912/app2/testApp2.cfc
Labels: testcase

#1510 Added a testcase to calling CFC using relative path inside the long-running thread for LDEV-3802
  test/tickets/LDEV3802.cfc
  test/tickets/LDEV3802/LDEV3802.cfm
  test/tickets/LDEV3802/sub/test.cfc
Labels: testcase

#1498 Added a testcase to comparison and arithmetic operations with char for LDEV-3786
  test/tickets/LDEV3786.cfc
Labels: testcase

#1416 update core-cfml.tld application attribute mail to mailservers and add modifier attribute to cffunction
  core/src/main/java/resource/tld/core-cfml.tld
Labels: documentation

#1392 Added to testcase Calling Webservice with returnType XML for LDEV-3629
  test/tickets/LDEV3629.cfc
  test/tickets/LDEV3629/test.cfc
Labels: testcase

#1652 Added a testcase to cfoutput with tag attribute in Application for LDEV-4008
  test/tickets/LDEV4008.cfc
  test/tickets/LDEV4008/Application.cfc
  test/tickets/LDEV4008/LDEV4008.cfm
Labels: testcase

#1641 Fix grammar and word casing in `README.md`
  README.md
Labels: documentation

#1629 Use lowercase CF tag
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#1631 Added a testcase to listFilter() and adjust some list functions testcases for LDEV-3747
  test/functions/StringSome.cfc
  test/functions/listEach.cfc
  test/functions/listEvery.cfc
  test/functions/listFilter.cfc
  test/functions/listReduce.cfc
  test/functions/listSome.cfc
Labels: testcase

#1617 Improved the message for output the component with debug enabled
  core/src/main/cfml/context/component-dump.cfm
  core/src/main/java/resource/context/component-dump.cfm
Labels: enhancement

#1190 Add more detailed Extension logging LDEV-3277
  core/src/main/cfml/context/admin/ext.functions.cfm
  core/src/main/java/lucee/runtime/config/XMLConfigAdmin.java
Labels: enhancement, exceptions

#1177 remove old java concurrent support LDEV-3263
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: shrink

#1308 remove applet support LDEV-3343
  core/src/main/cfml/context/lucee-applet.cfm
  core/src/main/cfml/context/lucee-applet.jar
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  core/src/main/java/lucee/runtime/tag/Applet.java
  core/src/main/java/lucee/runtime/tag/Form.java
  core/src/main/java/resource/tld/core-cfml.tld
Labels: shrink, build

#1588 Added a fix:Server Admin Settings - Logging page to show the edit option for LDEV-3821
  core/src/main/java/resource/context/admin/logging/appender/ConsoleAppender.cfc
  core/src/main/java/resource/context/admin/logging/appender/DatasourceAppender.cfc
  core/src/main/java/resource/context/admin/logging/appender/ResourceAppender.cfc
Labels: bugfix

#1657 LDEV-4018 build : remove dependency on compress and esapi for tests
  test/bootstrap-tests.cfm
Labels: build

#1672 Added a testcase to duplicate() with ORM object for LDEV-2862 (lucee 5.3)
  test/tickets/LDEV2862.cfc
  test/tickets/LDEV2862/Application.cfc
  test/tickets/LDEV2862/test.cfc
  test/tickets/LDEV2862/test.cfm
  test/tickets/LDEV2862/test2.cfc
Labels: testcase

#1674 Added a testcase to serializeJSON() with different query column types for LDEV3406 (lucee-5.3)
  test/tickets/LDEV3406.cfc
  test/tickets/LDEV3406/Application.cfc
  test/tickets/LDEV3406/LDEV3406.cfm
Labels: testcase

#1670 Added a testcase to expandpath('path') with slash(/) before creating a mapping in the onRequest for LDEV-4031
  test/tickets/LDEV4031.cfc
  test/tickets/LDEV4031/Application.cfc
  test/tickets/LDEV4031/LDEV4031.cfm
  test/tickets/LDEV4031/moduleDir/MyService.cfc
Labels: testcase

#1679 LDEV-4028 add greenmail to build for mail tests including tls/ssl
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/tags/Imap.cfc
  test/tickets/LDEV0910.cfc
  test/tickets/LDEV1537.cfc
  test/tickets/LDEV1537/Application.cfc
  test/tickets/LDEV1537/test.cfm
  test/tickets/LDEV1537/test2.cfm
  test/tickets/LDEV1537/test3.cfm
  test/tickets/LDEV1537/test4.cfm
  test/tickets/LDEV1537/test5.cfm
  test/tickets/LDEV3687.cfc
  test/tickets/LDEV3687/Application.cfc
  test/tickets/LDEV3687/LDEV3687.cfm
Labels: testcase, build

#1675 Added testcase SerializeJSON serializes boolean LDEV-3410
  test/tickets/LDEV3410.cfc
  test/tickets/LDEV3410/Test.cfc
Labels: testcase
