Repository lucee/Lucee, pull requests merged in 2022-02, with the labels that each got.

#1555 updated the testcase jira-2854 to fail instead of throwing byte code error
  test/jira/Jira2854.cfc
  test/jira/jira2854/test.cfc
Labels: testcase, bugfix

#1538 LDEV-3819 update Apache Commons Codec to 1.15
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
  test/functions/Metaphone.cfc
  test/functions/SoundEx.cfc
Labels: enhancement, testcase

#1556 Added a fix and testcase for CFC Metadata to trim implements and extends attributes in LDEV-3338
  core/src/main/java/lucee/runtime/type/util/ListUtil.java
  test/tickets/LDEV3338.cfc
  test/tickets/LDEV3338/A.cfc
  test/tickets/LDEV3338/B.cfc
  test/tickets/LDEV3338/IMPLwithSpace.cfc
  test/tickets/LDEV3338/IMPLwithoutSpace.cfc
  test/tickets/LDEV3338/X.cfc
Labels: testcase, bugfix

#1544 Added a fix:mail.log to include mail server info too for LDEV-3839
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
Labels: enhancement

#1560 update maven build plugins
  loader/pom.xml
Labels: build

#1543 Bug fix: Removed the default value CGIReadOnly=true in cfapplication for LDEV-3841
  core/src/main/java/resource/tld/core-cfml.tld
  test/tickets/LDEV3841.cfc
Labels: bugfix

#1561 LDEV-3841 revert changes
  core/src/main/java/resource/tld/core-cfml.tld
  test/tickets/LDEV3841.cfc
Labels: bugfix

#1559 LDEV-3865 add support for setting a custom context root via lucee.cli.contextRoot
  loader/src/main/java/lucee/runtime/script/BaseScriptEngineFactory.java
Labels: bugfix

#1565 Added a fix to the application mail listener logs NPE in remoteClient.log for LDEV-3853
  core/src/main/java/lucee/runtime/spooler/CFMLSpoolerTaskListener.java
Labels: exceptions, bugfix

#1564 Added a fix to add the ESAPI/Compress extension in not installed list correctly for LDEV-3695
  core/src/main/cfml/context/admin/ext.applications.list.cfm
Labels: bugfix

#1571 Added a testcase to Array & struct functions
  test/functions/arrayEvery.cfc
  test/functions/arrayMap.cfc
  test/functions/arrayReduce.cfc
  test/functions/arraySome.cfc
  test/functions/listEach.cfc
  test/functions/listEvery.cfc
  test/functions/listMap.cfc
  test/functions/listReduce.cfc
  test/functions/listSome.cfc
  test/functions/structEach.cfc
  test/functions/structEvery.cfc
  test/functions/structMap.cfc
  test/functions/structReduce.cfc
  test/functions/structSome.cfc
Labels: testcase

#1575 fix LSCurrency test on windows
  test/functions/LSCurrencyFormat.cfc
Labels: testcase

#1557 Added a testcase to check transaction with ORM and query for LDEV-3859 & LDEV-3860
  test/tickets/LDEV3860.cfc
  test/tickets/LDEV3860/Application.cfc
  test/tickets/LDEV3860/LDEV3859.cfm
  test/tickets/LDEV3860/LDEV3860.cfm
  test/tickets/LDEV3860/test.cfc
Labels: testcase

#1574 Added a fix to Admin - update Logging to Datasource Appender for LDEV-3825
  core/src/main/java/resource/context/admin/logging/appender/DatasourceAppender.cfc
Labels: bugfix
