Repository lucee/Lucee, pull requests merged in 2022-08, with the labels that each got.

#1741 LDEV-3431 fix javax.mail.Provider: com.sun.mail.imap.IMAPProvider not a subtype
  ant/build-core.xml
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
  test/tags/Imap.cfc
Labels: enhancement, testcase, bugfix, build

#1742 LDEV-4115 imap test case query column checks
  test/tags/Imap.cfc
Labels: testcase

#1743 Added a fix to show and preserve the logging layout if the layout cfcmissing for LDEV-4112
  core/src/main/cfml/context/admin/server.logging.create.cfm
Labels: enhancement

#1744 Added a testcase to check the structGet() with numeric key for LDEV-4118
  test/tickets/LDEV4118.cfc
Labels: testcase

#1361 Added a fix for getComponentMetadata to returns abstract details too in LDEV-3560
  core/src/main/java/lucee/runtime/ComponentImpl.java
  core/src/main/java/lucee/runtime/type/util/KeyConstants.java
  test/tickets/LDEV3560.cfc
  test/tickets/LDEV3560/testAbstract.cfc
Labels: enhancement

#691 Cfschedule list returns wrong urls LDEV-2309
  core/src/main/java/lucee/runtime/tag/Schedule.java
  test/tickets/LDEV2309.cfc
Labels: bugfix

#1345 Added a fix to support json and object in isValid() in LDEV-566
  core/src/main/java/lucee/runtime/op/Decision.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/IsObject.cfc
  test/functions/IsValid.cfc
Labels: enhancement, testcase

#1665 Set minimum interval requirement to 1(lucee 5.3)
  core/src/main/java/lucee/runtime/schedule/ScheduleTaskImpl.java
Labels: enhancement

#1745 Added a testcase to check UDF has multiple arguments with same name for LDEV-4122
  test/tickets/LDEV4122.cfc
  test/tickets/LDEV4122/LDEV4122.cfm
Labels: testcase

#1412 Added a fix to getMetadata() add final key for final component in LDEV-3670
  core/src/main/java/lucee/runtime/ComponentImpl.java
  core/src/main/java/lucee/runtime/type/util/KeyConstants.java
  test/tickets/LDEV3670.cfc
  test/tickets/LDEV_3670/testFinal.cfc
Labels: testcase, bugfix

#1746 Added a fix for settings/proxy css issue and also changed the content for LDEV-3268
  core/src/main/cfml/context/admin/language.xml
  core/src/main/cfml/context/admin/resources/language/ch-be.xml
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/resources/language/nl.xml
  core/src/main/cfml/context/admin/server.proxy.cfm
  core/src/main/java/resource/context/admin/resources/language/en.xml
  test/components/Administrator/en.xml
Labels: enhancement

#1566 support custom struct as additional args for updateDatasource() in Administrator.cfc for LDEV-3469
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
Labels: bugfix

#1750 Added a testcase to onApplicationStart() with using application scope in ORM event handler for LDEV-3883
  test/tickets/LDEV3883.cfc
  test/tickets/LDEV3883/Application.cfc
  test/tickets/LDEV3883/LDEV3883.cfm
  test/tickets/LDEV3883/eventHandler.cfc
  test/tickets/LDEV3883/person.cfc
  test/tickets/LDEV3883/test.cfc
Labels: testcase

#1747 Added a testcase to check the default property value to overide NULL value on ORM Entity For LDEV-4121
  test/tickets/LDEV4121.cfc
  test/tickets/LDEV4121/Application.cfc
  test/tickets/LDEV4121/LDEV4121.cfm
  test/tickets/LDEV4121/org.cfc
Labels: testcase

#1664 Added a tests to cffile tag
  test/tags/File.cfc
  test/tags/directory.cfc
Labels: testcase

#1661 Added a testcase to check the stacktrace of serialize/deSerialize struct of the original exception for LDEV-4021
  test/tickets/LDEV4021.cfc
Labels: testcase

#1660 Added a testcase to access the lazy-loaded ORM entity after the transaction ends for LDEV-4017
  test/tickets/LDEV4017.cfc
  test/tickets/LDEV4017/Application.cfc
  test/tickets/LDEV4017/LDEV4017.cfm
  test/tickets/LDEV4017/Person.cfc
  test/tickets/LDEV4017/Thought.cfc
Labels: testcase

#1663 Added a testcase to check java code in lucee using cfjava/java block for LDEV-4001
  test/tickets/LDEV4001.cfc
  test/tickets/LDEV4001/LDEV4001.cfm
Labels: testcase

#1621 Added a fix to reMatch/reMatchNoCase regression with empty string for LDEV-3703 (lucee 5.3)
  core/src/main/java/lucee/runtime/regex/Perl5Util.java
  test/tickets/LDEV3703.cfc
Labels: testcase, bugfix

#1748 Added a fix to reMatch/reMatchNoCase regression with empty string for LDEV-3703 (lucee 5.3.9)
  core/src/main/java/lucee/runtime/regex/Perl5Util.java
  test/tickets/LDEV3703.cfc
Labels: testcase, bugfix

#1616 Added a fix to java regex engine incompatibility issue in LDEV-3690 & LDEV-3533 (lucee-5.3)
  core/src/main/java/lucee/runtime/regex/JavaRegex.java
  test/tickets/LDEV3690.cfc
Labels: testcase, bugfix

#1418 Added a fix to java regex engine incompatibility issue in LDEV-3690
  core/src/main/java/lucee/runtime/regex/JavaRegex.java
  test/tickets/LDEV3690.cfc
Labels: testcase, bugfix

#1752 Added a bit corrections to fld and precise argument in decryptBinary() for LDEV-4101
  core/src/main/java/lucee/runtime/functions/other/Decrypt.java
  core/src/main/java/resource/fld/core-base.fld
Labels: bugfix, tests required

#1667 Added a fix to support the offset argument in String.listRest() member function for LDEV-4024
  core/src/main/java/lucee/runtime/functions/list/ListRemoveDuplicates.java
  core/src/main/java/lucee/runtime/functions/list/ListRest.java
  test/functions/ListRest.cfc
Labels: testcase, bugfix

#1753 Added a test for ordered-casesensitive struct with Implicit notation in LDEV-3133 testcase
  test/tickets/LDEV3133.cfc
  test/tickets/LDEV3133/test.cfm
  test/tickets/_LDEV3133.cfc
Labels: testcase

#1754 Added a tests to Encrypt(), Decrypt(), encryptBinary(), decryptBinary() with precise argument for LDEV-4101
  test/functions/Decrypt.cfc
  test/functions/DecryptBinary.cfc
  test/functions/Encrypt.cfc
  test/functions/EncryptBinary.cfc
Labels: testcase

#1761 update pdf, compress and image extensions 5.3.10.54
  core/src/main/java/META-INF/MANIFEST.MF
  loader/build.xml
  loader/pom.xml
  test/tickets/LDEV1989.cfc
Labels: enhancement

#1762 add introduced dates to functions and arguments
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/fld/core-cfml.fld
  core/src/main/java/resource/fld/core-lucee.fld
Labels: documentation

#1763 add introduced for tags and attributes
  core/src/main/java/resource/tld/core-base.tld
  core/src/main/java/resource/tld/core-cfml.tld
  core/src/main/java/resource/tld/core-lucee.tld
Labels: documentation

#777 consistent formatting for execution times, classic debug template LDEV-2531
  core/src/main/java/resource/context/admin/debug/Classic.cfc
Labels: enhancement

#1769 LDEV-4155 testcase for replaceNoCase problem
  test/tickets/LDEV4155.cfc
Labels: testcase

#1770 Added a testcase to isWithinTransaction() for LDEV-4146
  test/tickets/IsWithinTransaction.cfc
Labels: testcase
