Repository lucee/Lucee, pull requests merged in 2022-09, with the labels that each got.

#1782 LDEV-4179 add broad test set of support for various image formats
  test/artifacts/images/1.sm.png
  test/artifacts/images/1_webp_a.sm.png
  test/artifacts/images/1_webp_a.webp
  test/artifacts/images/1_webp_ll.sm.png
  test/artifacts/images/1_webp_ll.webp
  test/artifacts/images/2_webp_a.webp
  test/artifacts/images/2_webp_ll.webp
  test/artifacts/images/4.sm.jpg
  test/artifacts/images/image1.heic
  test/artifacts/images/image2.heic
  test/artifacts/images/image3.heic
  test/artifacts/images/image4.heic
  test/artifacts/images/image5.png
  test/artifacts/images/sample1.heic
  test/artifacts/images/small-sample.webp
  test/artifacts/images/web-platform-tests/anim-gr.gif
  test/artifacts/images/web-platform-tests/anim-gr.png
  test/artifacts/images/web-platform-tests/anim-poster-gr.png
  test/artifacts/images/web-platform-tests/anim-tao.png
  test/artifacts/images/web-platform-tests/apng.png
  test/artifacts/images/web-platform-tests/arrow-oriented-upright.jpg
  test/artifacts/images/web-platform-tests/background.png
  test/artifacts/images/web-platform-tests/black-rectangle.png
  test/artifacts/images/web-platform-tests/blue-area.png
  test/artifacts/images/web-platform-tests/blue-border.png
  test/artifacts/images/web-platform-tests/blue.png
  test/artifacts/images/web-platform-tests/blue96x96.png
  test/artifacts/images/web-platform-tests/clear-100x50.png
  test/artifacts/images/web-platform-tests/fail.gif
  test/artifacts/images/web-platform-tests/ggrr-256x256.png
  test/artifacts/images/web-platform-tests/green-100x50.png
  test/artifacts/images/web-platform-tests/green-16x16.png
  test/artifacts/images/web-platform-tests/green-1x1.png
  test/artifacts/images/web-platform-tests/green-256x256.png
  test/artifacts/images/web-platform-tests/green-2x2.png
  test/artifacts/images/web-platform-tests/green.png
  test/artifacts/images/web-platform-tests/grgr-256x256.png
  test/artifacts/images/web-platform-tests/movie_300_frame_0.png
  test/artifacts/images/web-platform-tests/pattern.mp4
  test/artifacts/images/web-platform-tests/pattern.ogv
  test/artifacts/images/web-platform-tests/pattern.png
  test/artifacts/images/web-platform-tests/red-16x16.png
  test/artifacts/images/web-platform-tests/red.png
  test/artifacts/images/web-platform-tests/redtransparent.png
  test/artifacts/images/web-platform-tests/rgrg-256x256.png
  test/artifacts/images/web-platform-tests/rrgg-256x256.png
  test/artifacts/images/web-platform-tests/smiley.png
  test/artifacts/images/web-platform-tests/threecolors.png
  test/artifacts/images/web-platform-tests/transparent.png
  test/artifacts/images/web-platform-tests/transparent50.png
  test/artifacts/images/web-platform-tests/webp-animated.webp
  test/artifacts/images/web-platform-tests/wide-gamut-pattern.png
  test/artifacts/images/web-platform-tests/yellow.png
  test/artifacts/images/web-platform-tests/yellow75.png
  test/general/ImageFormatSupport.cfc
Labels: testcase

#1781 Added a correction to the error messagge for Array.set() in LDEV-4176
  core/src/main/java/lucee/runtime/functions/arrays/ArraySet.java
Labels: exceptions

#1787 LDEV-4173 fix mongodb tests
  test/functions/CacheClear.cfc
Labels: testcase

#1785 Correct spelling / grammar for PRECISE argument.
  core/src/main/java/resource/fld/core-base.fld
Labels: documentation

#1789 Added a testcase to check string column with numeric values and trailing space for LDEV-4186
  test/tickets/LDEV4186.cfc
Labels: testcase

#1788 Added a testcase to isWithinTransaction() with native Hibernate transaction
  test/tickets/LDEV4185.cfc
  test/tickets/LDEV4185/Application.cfc
  test/tickets/LDEV4185/LDEV4185.cfm
  test/tickets/LDEV4185/test4185.cfc
Labels: testcase

#1793 Minor tweak, to improve readability of PRECISE argument description.
  core/src/main/java/resource/fld/core-base.fld
Labels: documentation

#1783 catched the bundled error and skipped this process for other extensions for LDEV-3890
  core/src/main/cfml/context/admin/ext.applications.cfm
  core/src/main/cfml/context/admin/ext.functions.cfm
  core/src/main/cfml/context/admin/ext.providers.cfm
Labels: bugfix

#1806 QoQ shouldn't fall back to HSQLDB after queryparam error
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/exp/DatabaseException.java
  core/src/main/java/lucee/runtime/exp/IllegalQoQException.java
  core/src/main/java/lucee/runtime/tag/util/QueryParamConverter.java
  test/tickets/LDEV3878.cfc
Labels: testcase, bugfix

#1802 update extensions for 5.3.10
  core/src/main/java/META-INF/MANIFEST.MF
Labels: enhancement
