Repository lucee/Lucee, pull requests merged in 2022-07, with the labels that each got.

#1686 LDEV-4029 add test case for https connection to maven
  test/tickets/LDEV4029.cfc
Labels: testcase

#1683 Added a missing keys to language file for LDEV-4058
  core/src/main/cfml/context/admin/debugging.settings.cfm
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/services.schedule.edit.cfm
  core/src/main/cfml/context/admin/services.schedule.list.cfm
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: bugfix

#1687 Added a fix to updating the scheduled task to remove useragent key from the config file if that value is not provided for LDEV-2999
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1688 LDEV-3448 test case change session cookie defaults to be httpOnly; samesite=lax
  test/tickets/LDEV3448.cfc
  test/tickets/LDEV3448/session-cfml-no-httpOnly/Application.cfc
  test/tickets/LDEV3448/session-cfml-no-httpOnly/index.cfm
  test/tickets/LDEV3448/session-cfml/Application.cfc
  test/tickets/LDEV3448/session-cfml/index.cfm
  test/tickets/LDEV3448/session-jee/Application.cfc
  test/tickets/LDEV3448/session-jee/index.cfm
Labels: testcase

#1692 Added a transaction with Exclusive connections for request option enabled for LDEV-4056
  test/tickets/LDEV4056.cfc
  test/tickets/LDEV4056/Application.cfc
  test/tickets/LDEV4056/LDEV4056.cfm
Labels: testcase

#1689 Improve the error messages displayed for hex encoding.
  core/src/main/java/lucee/runtime/coder/HexCoder.java
Labels: exceptions

#1603 LDEV-3911 add extended cookie tests
  test/tags/cookie.cfc
  test/tags/cookie/extendedData.cfm
  test/tags/cookie/extendedTest.cfm
Labels: testcase

#1701 LDEV-4076 tests, also report nested specErrors
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: testcase, build

#1685 LDEV-4060 update felix to 7.0.5
  core/pom.xml
  loader/pom.xml
Labels: enhancement

#1695 Added a fix to cftimer to support console type for LDEV-4066
  core/src/main/java/lucee/runtime/tag/Timer.java
  core/src/main/java/resource/tld/core-base.tld
Labels: enhancement

#1658 Added a fix and testcase to cfafmin action=getcharset() to return values correctly for LDEV-3224
  core/src/main/java/lucee/runtime/tag/Admin.java
  test/tickets/LDEV3224.cfc
Labels: testcase, bugfix

#1242 improve error messages - member functions LDEV-3383
  core/src/main/java/lucee/commons/lang/ExceptionUtil.java
  core/src/main/java/lucee/runtime/functions/system/SystemCacheClear.java
  core/src/main/java/lucee/runtime/tag/Log.java
  core/src/main/java/lucee/runtime/type/BIF.java
  core/src/main/java/lucee/runtime/type/scope/UndefinedImpl.java
  core/src/main/java/lucee/runtime/type/util/MemberUtil.java
  core/src/main/java/lucee/runtime/type/util/StructSupport.java
  test/tickets/LDEV3167.cfc
Labels: exceptions, Conflict / Review

#1304 Added a fix for remove scheduledtask exception in LDEV-3449
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1354 Added a fix: CFPOP to retrieves the message/rfc822 data's for LDEV-3548
  .github/workflows/main.yml
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
  test/tickets/LDEV3548.cfc
  test/tickets/LDEV3548/sendMultipartMail.cfm
Labels: testcase, bugfix

#1604 Added a fix: _internalRequest() to include Content-Type and Content-Length for LDEV-3917
  core/src/main/java/lucee/runtime/functions/system/InternalRequest.java
  test/functions/InternalRequest.cfc
  test/functions/InternalRequest/content.cfm
Labels: enhancement, testcase

#1183 allow empty passwords for datasources LDEV-3272
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1693 Added a fix to deleting the cache in Admin cache page for LDEV-4059
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1703 LDEV-4078 update slf4j to 1.7.36
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#1318 LDEV-3418 - Feature/http connection manager gc - Fixes LDEV-2199
  core/src/main/java/lucee/commons/net/http/httpclient/HTTPEngine4Impl.java
  core/src/main/java/lucee/runtime/engine/Controler.java
  core/src/main/java/lucee/runtime/tag/Http.java
  core/src/main/java/resource/tld/core-base.tld
Labels: enhancement

#1707 LDEV-3380 bugfix debug thread config
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1709 I added a fix to check filewrite() to include the path in error if path not exist for LDEV-4081
  core/src/main/java/lucee/runtime/functions/file/FileWrite.java
  test/tickets/LDEV4081.cfc
Labels: exceptions, testcase, build

#1712 Added a testcase to cfsilent tag
  test/tags/Silent.cfc
  test/tags/cfsilent/cfsilent.cfm
Labels: testcase

#1713 Cleanup the mail testcase and modified to use greenmail
  test/tags/Mail.cfc
  test/tags/_Mail.cfc
Labels: testcase

#1714 Added a correction to LDEV-4081 testcase
  test/tickets/LDEV4081.cfc
Labels: testcase

#1351 Added a fix for hash() and tobase64() member function to throw correct error with struct and array
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV3556.cfc
Labels: bugfix, tests required

#1715 allow empty username for datasources LDEV-3272
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1169 allow least min value on negative index array LDEV-3258
  core/src/main/java/lucee/runtime/type/wrap/ListAsArray.java
  test/tickets/LDEV1836.cfc
  test/tickets/_LDEV1836.cfc
Labels: enhancement, bugfix, tests required

#1359 Changed query.addRow(), addColumn(), deleteRow(), deleteColumn() to returns updated query
  core/src/main/java/resource/fld/core-base.fld
  test/functions/QueryAddColumn.cfc
  test/functions/QueryAddRow.cfc
  test/functions/QueryDeleteColumn.cfc
  test/functions/QueryDeleteRow.cfc
  test/tags/query/QueryListener.cfc
Labels: enhancement, bugfix

#1403 Added a new function isFileObject() for LDEV-3651
  core/src/main/java/lucee/runtime/functions/decision/IsFileObject.java
  core/src/main/java/lucee/runtime/op/Decision.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/isFileObject.cfc
Labels: enhancement

#1475 Added a fix to XML.elemNew() for LDEV-2936
  core/src/main/java/lucee/runtime/op/Caster.java
  test/tickets/LDEV2936.cfc
Labels: bugfix

#1401 Added a new function ExtensionInfo() for LDEV-3599
  core/src/main/java/lucee/runtime/functions/system/ExtensionInfo.java
  core/src/main/java/resource/fld/core-base.fld
Labels: enhancement

#1526 🤖 TEST: Add tests for new events emitted in Hibernate 5.4
  test/orm/Hibernate.cfc
  test/orm/events/Application.cfc
  test/orm/events/eventHandler.cfc
  test/orm/events/index.cfm
Labels: testcase

#1690 Added a testcase to check lambda expression without the body({}) for LDEV-4062
  test/tickets/LDEV4062.cfc
  test/tickets/LDEV4062/LDEV4062.cfm
Labels: testcase

#1721 Added a fix to the issue in admin by LDEV-3581(lucee 6)
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#1724 Improve 6 build
  ant/build-core.xml
  ant/build-extensions.xml
  ant/build-utils.xml
  ant/build-warmup-test.xml
  core/src/main/java/META-INF/MANIFEST.MF
Labels: build

#1726 Added a testcase to deserialize the json with large number value for LDEV-4103
  test/tickets/LDEV4103.cfc
Labels: testcase

#1725 Added a testcase to check the MSSQL datetimeoffset field value for LDEV-1680
  test/tickets/LDEV1680.cfc
  test/tickets/LDEV1680/Application.cfc
  test/tickets/LDEV1680/LDEV1680.cfm
Labels: testcase

#1723 Added a fix to local docs member functions to show the return type correctly for LDEV-4104
  core/src/main/cfml/context/doc/objects.cfm
Labels: documentation, bugfix

#1699 Added a testcase to check large number value with more than 19 digits for LDEV-4070
  test/tickets/LDEV4070.cfc
Labels: testcase

#1696 Added a testcase to check this/variables scope calling from closure/lambda with ORM entity for LDEV-4067
  test/tickets/LDEV4067.cfc
  test/tickets/LDEV4067/Application.cfc
  test/tickets/LDEV4067/LDEV4067.cfm
  test/tickets/LDEV4067/test.cfc
Labels: testcase

#1733 LDEV-4004 test case for loop in queryEach callback is not thread safe
  test/tickets/LDEV4004-v2.cfc
  test/tickets/LDEV4004.cfc
Labels: testcase

#1729 Added a fix and testcase to cfafmin action=getcharset() to return vaues correctly for LDEV-3224 (lucee 6.0l)
  core/src/main/java/lucee/runtime/tag/Admin.java
  test/tickets/LDEV3224.cfc
Labels: testcase, bugfix

#1728 LDEV-4091 add datadog layout to the admin
  core/src/main/java/resource/context/admin/logging/layout/DatadogLayout.cfc
Labels: enhancement

#1697 Added a fix to cfhtmlhead/cfhmlbody with text attribute and body content for LDEV-3618
  core/src/main/java/lucee/runtime/tag/HtmlHeadBodyBase.java
  test/tickets/LDEV3618.cfc
  test/tickets/LDEV3618/test.cfm
Labels: testcase, bugfix

#1668 LDEV-4027 change cfquery attribute tags to not be hidden
  core/src/main/java/resource/tld/core-base.tld
Labels: documentation

#1666 Added a testcase to arrayEach() with array that has null values for LDEV-4023
  test/tickets/LDEV4023.cfc
Labels: testcase

#1567 Added a correction in Administrator.cfc (lucee-6.0)
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
Labels: bugfix

#1502 Added a fix to Scheduled tasks to passing Authorization header for LDEV-2925
  core/src/main/java/lucee/runtime/schedule/ExecutionThread.java
  test/tickets/LDEV2925.cfc
Labels: bugfix

#1734 LDEV-4108 better OSGI bundle exception and console logging
  core/src/main/java/lucee/runtime/osgi/OSGiUtil.java
Labels: exceptions, build

#1735 LDEV-4117 Add ldap service and tests to build
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/tags/LDAP.cfc
Labels: testcase, build

#1736 LDEV-4117 switch to rroemhild/test-openldap for build
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/tags/LDAP.cfc
Labels: testcase, build

#1738 LDEV-4108 better OSGI bundle exceptions
  ant/build-core.xml
  core/src/main/java/lucee/runtime/jsr223/ScriptEngineImpl.java
  core/src/main/java/lucee/runtime/osgi/OSGiUtil.java
Labels: exceptions, build
