Repository lucee/Lucee, pull requests merged in 2022-01, with the labels that each got.

#1398 LDEV-3640 QoQ needs to preserve nulls internally regardless of full null support
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/sql/QueryPartitions.java
  test/tickets/LDEV3042.cfc
  test/tickets/LDEV3640.cfc
Labels: testcase, bugfix

#1513 LDEV-3810 add trace logging for cfhttp calls (5.3)
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: enhancement

#1503 update Felix 6.0.5 for Java > 15
  .github/workflows/main.yml
  core/pom.xml
  loader/pom.xml
Labels: enhancement

#1508 LDEV-3804 Throw exception, don't return it
  core/src/main/java/lucee/commons/lang/ClassUtil.java
Labels: bugfix

#1518 update format exception for missing existing keys
  core/src/main/java/lucee/runtime/type/scope/storage/IKStorageScopeSupport.java
  core/src/main/java/lucee/runtime/type/util/StructSupport.java
Labels: exceptions

#1517 LDEV-3801
  core/src/main/java/lucee/runtime/sql/Select.java
  test/tickets/LDEV3801.cfc
Labels: bugfix

#1516 LDEV-3522 QoQ cast()/convert() functions not fully implemented
  core/src/main/java/lucee/runtime/db/QoQ.java
  test/tickets/LDEV3522.cfc
Labels: bugfix

#1505 LDEV-3712 Update oracle bundlename
  core/src/main/java/lucee/runtime/db/DBUtil.java
  test/_setupTestServices.cfc
Labels: bugfix

#1407 Added a fix to show alert for internet connection in web admin
  core/src/main/cfml/context/admin/ext.applications.detail.cfm
  core/src/main/cfml/context/admin/ext.applications.list.cfm
  core/src/main/cfml/context/admin/resources/language/en.xml
Labels: bugfix

#1174 Added a fix to show image object in extensionList function for LDEV-3261
  core/src/main/java/lucee/runtime/functions/system/ExtensionList.java
  core/src/main/java/resource/fld/core-base.fld
Labels: enhancement

#602 Bug fix for adding multiple file access directories in one request
  core/src/main/cfml/context/admin/navigation.cfm
  core/src/main/cfml/context/admin/security.access.form.cfm
Labels: bugfix

#1522 LDEV-3166 update jsch to 0.1.55
  core/pom.xml
  loader/build.xml
  loader/pom.xml
  test/tags/FTP.cfc
Labels: enhancement

#1525 LDEV-3822 stricter QoQ order by validation
  core/src/main/java/lucee/runtime/sql/Selects.java
  test/tickets/LDEV3801.cfc
  test/tickets/LDEV3822.cfc
Labels: testcase, bugfix

#1528 LDEV-2772 add scope cascading checks with query scope
  test/tickets/LDEV2772.cfc
  test/tickets/LDEV2772/searchResults.cfm
Labels: testcase

#1529 LDEV-3830 remove optimization to ensure distincts
  core/src/main/java/lucee/runtime/db/QoQ.java
  test/tickets/LDEV3830.cfc
Labels: testcase, bugfix

#1530 use unique s3 bucket names for tests
  test/extension/S3.cfc
  test/general/Resources.cfc
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
Labels: testcase, build

#1527 LDEV-3829 argon2 fix memory argument handling
  core/src/main/java/lucee/runtime/functions/other/GenerateArgon2Hash.java
Labels: bugfix

#1542 LDEV-3844 remove getConfigSettings
  core/src/main/java/lucee/runtime/functions/system/GetConfigSettings.java
  core/src/main/java/resource/context/admin/logging/appender/ConsoleAppender.cfc
  core/src/main/java/resource/context/admin/logging/appender/DatasourceAppender.cfc
  core/src/main/java/resource/context/admin/logging/appender/ResourceAppender.cfc
  core/src/main/java/resource/context/admin/logging/layout/ClassicLayout.cfc
  core/src/main/java/resource/context/admin/logging/layout/HTMLLayout.cfc
  core/src/main/java/resource/context/admin/logging/layout/PatternLayout.cfc
  core/src/main/java/resource/context/admin/logging/layout/XMLLayout.cfc
  core/src/main/java/resource/fld/core-base.fld
Labels: bugfix

#1537 LDEV-3536 update JNA to 5.10.0
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
  test/tags/test-orientation.pdf
Labels: enhancement

#1548 LDEV-3851 build: test latest core with stable loader (5.3)
  ant/build-core.xml
  ant/build-test-stable-loader.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/build.xml
Labels: testcase, build

#1547 LDEV-3851 build: test latest core with stable loader
  ant/build-core.xml
  ant/build-extensions.xml
  ant/build-test-stable-loader.xml
Labels: testcase, build

#1549 run tests with different java versions
  .github/workflows/main-java-11.yml
  .github/workflows/main-java-14.yml
  .github/workflows/main-java-17.yml
  .github/workflows/main-java-8.yml
  .github/workflows/main.yml
  ant/build-core.xml
Labels: build

#1550 updated run tests with different java versions
  .github/workflows/main-java-11.yml
  .github/workflows/main-java-14.yml
  .github/workflows/main-java-17.yml
  .github/workflows/main-java-8.yml
  .github/workflows/main.yml
  ant/build-core.xml
  test/run-tests.cfm
Labels: build

#1551 fix build process on windows
  .github/workflows/main.yml
  ant/build-core.xml
Labels: build

#1552 fix build process on windows
  .github/workflows/main.yml
  ant/build-core.xml
Labels: build
