Repository lucee/Lucee, pull requests merged in 2022-12, with the labels that each got.

#1889 Added a testcase to check QoQ HAVING clause in non-grouped aggregate select for LDEV-4300
  test/tickets/LDEV4300.cfc
Labels: testcase

#1888 Added a testcase to lTrim()
  test/functions/Day.cfc
  test/functions/LTrim.cfc
Labels: testcase

#1826 Added a function QueryToStruct() for LDEV-3249
  core/src/main/java/lucee/runtime/functions/query/QueryToStruct.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/QueryToStruct.cfc
Labels: enhancement, testcase

#1876 LDEV-2395 FileGetMimeType throw when strict on non existent/empty file
  core/src/main/java/lucee/runtime/functions/file/FileGetMimeType.java
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV2083.cfc
  test/tickets/LDEV2395.cfc
Labels: enhancement, testcase, bugfix

#1874 LDEV-4272 add trace logging for cfabort
  core/src/main/java/lucee/runtime/tag/Abort.java
Labels: enhancement

#1895 Added testcase to check lsIsDate() function with locale "english(uk)" for LDEV-4305
  test/tickets/LDEV4305.cfc
Labels: testcase

#1898 bugfix: GHA clean / from ref name for junit artifact naming
  .github/workflows/main.yml
Labels: build

#1831 Added a fix to always include a charset key in cfhttp result for LDEV-3678 (lucee 6.0)
  core/src/main/java/lucee/runtime/tag/Http.java
  test/tickets/LDEV3678.cfc
Labels: testcase, bugfix

#1797 Added a fix and testcase to support the mask 'ISO' in dateFormat() for LDEV-4198
  core/src/main/java/lucee/runtime/format/DateFormat.java
  core/src/main/java/resource/fld/core-cfml.fld
  test/tickets/LDEV4198.cfc
Labels: enhancement, testcase

#1795 Added a fix to parseDateTime() with format 'iso' for LDEV-4196
  core/src/main/java/lucee/runtime/functions/displayFormatting/DateTimeFormat.java
  test/tickets/LDEV4185.cfc
  test/tickets/LDEV4196.cfc
Labels: testcase, bugfix

#1866 Added a delimiter attribute to cfpop/cfimap for LDEV-4247
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
  core/src/main/java/lucee/runtime/tag/_Mail.java
  core/src/main/java/lucee/runtime/type/util/ListUtil.java
  core/src/main/java/resource/tld/core-base.tld
  test/tickets/LDEV4247.cfc
Labels: enhancement, testcase

#1897 Added missing argument descriptions for functions in Lucee core. Part 1.
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/fld/core-cfml.fld
Labels: documentation

#1896 LDEV-4299 switch to jsch fork mwiede/jsch
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#1900 LDEV-3678 avoid NPE with cfhttp charset
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: bugfix

#1902 LDEV-4102 enable LUCEE_ENABLE_WARMUP for single mode
  ant/build-warmup-test.xml
  core/src/main/java/lucee/runtime/engine/CFMLEngineImpl.java
Labels: bugfix

#1904 add test run summary to GHA summary
  test/_setupTestServices.cfc
  test/run-tests.cfm
Labels: build

#1905 Added a fix to add a regex config in GetApplicationSettings() for LDEV-4310
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
Labels: enhancement

#1894 LDEV-4308 fix orm pre-insert test
  test/jira/Jira2049.cfc
Labels: testcase, bugfix

#1914 LDEV-4336 Fix spelling
  test/tickets/LDEV3860.cfc
Labels: documentation, testcase

#1915 LDEV-1339 Fix spelling
  test/tickets/LDEV1339.cfc
Labels: testcase

#1911 LDEV-4333 add getApplicationSettings( onlySupported=boolean )
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/getApplicationSettings.cfc
  test/functions/getApplicationSettings/Application.cfc
  test/functions/getApplicationSettings/onlySupported.cfm
  test/functions/getApplicationSettings/suppressFunction.cfm
  test/functions/getApplicationSettings/unSupported.cfm
Labels: enhancement, testcase

#1918 Added a testcase to check cfqueryparam with scale attribute for LDEV-4337
  test/tickets/LDEV4337.cfc
  test/tickets/LDEV4337/Application.cfc
  test/tickets/LDEV4337/LDEV4337.cfm
Labels: testcase

#708 cflocation automatically encodes url before redirecting LDEV-2164
  core/src/main/java/lucee/runtime/tag/Http.java
  core/src/main/java/lucee/runtime/tag/Location.java
  core/src/main/java/resource/library/function/location.cfm
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix

#1069 avoid casting debugging numbers to to strings LDEV-3071
  core/src/main/java/lucee/runtime/debug/DebuggerImpl.java
Labels: enhancement

#1923 LDEV-2900 enable cfcookie samesite tag defaults
  core/src/main/cfml/context/admin/Application.cfc
  core/src/main/java/resource/tld/core-base.tld
  test/tickets/LDEV2900.cfc
  test/tickets/LDEV2900/tag-defaults/Application.cfc
  test/tickets/LDEV2900/tag-defaults/index.cfm
Labels: testcase, bugfix

#1922 Added a testcase to setting the default value in the primary key in ORM entity for LDEV-3907
  test/tickets/LDEV3907.cfc
  test/tickets/LDEV3907/Application.cfc
  test/tickets/LDEV3907/Brand.cfc
  test/tickets/LDEV3907/LDEV3907.cfm
Labels: testcase

#1901 Fixing a minor formatting issue.
  core/src/main/java/lucee/runtime/interpreter/CFMLExpressionInterpreter.java
Labels: exceptions

#1903 Added a fix to return a charset value in cfhttp result for LDEV-3678
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: bugfix
