Repository lucee/Lucee, pull requests merged in 2022-10, with the labels that each got.

#1827 Added a correction to the error message for Array.set() in LDEV-4176 (lucee 6.0)
  core/src/main/java/lucee/runtime/functions/arrays/ArraySet.java
Labels: exceptions

#1815 LDEV-4204 - make "children" a thread safe type - 5.3.8
  core/src/main/java/lucee/runtime/PageContextImpl.java
Labels: bugfix

#1839 LDEV-4226 improve Image Format tests
  test/functions/ImageFormats.cfc
Labels: testcase

#1854 Added a testcase to calling static methods from an abstract component for LDEV-4246
  test/tickets/LDEV4246.cfc
  test/tickets/LDEV4246/abstract.cfc
Labels: testcase

#1855 Added a testcase to cfpop/cfimap delimiter attribute for LDEV-4247
  test/tickets/LDEV4247.cfc
  test/tickets/LDEV4247/LDEV4247.cfm
  test/tickets/LDEV4247/sendMails.cfm
Labels: testcase

#1814 Added a testcase to check static scope with extended component source code changes for LDEV-4212
  test/tags/Query.cfc
  test/tickets/LDEV4212.cfc
  test/tickets/LDEV4212/LDEV4212.cfm
Labels: testcase

#1834 Added a testcase to check getMetaData() for LDEV3671
  test/tickets/LDEV3671.cfc
  test/tickets/LDEV3671/test3671.cfc
Labels: testcase

#1833 Added a testcase to check xmlValidate() for LDEV-2909
  test/tickets/LDEV2909.cfc
Labels: testcase

#1825 Added a testcase to check booleanFormat() with nested structure for LDEV-2899
  test/tickets/LDEV2899.cfc
Labels: testcase

#1776 Added a testcase to onSessionEnd() with sessionInvalidate() for LDEV-4166
  test/tickets/LDEV4166.cfc
  test/tickets/LDEV4166/Jee_session_Invalidate/Application.cfc
  test/tickets/LDEV4166/Jee_session_Invalidate/test_jee_sessionEnd.cfm
  test/tickets/LDEV4166/cfml_session_Invalidate/Application.cfc
  test/tickets/LDEV4166/cfml_session_Invalidate/test_cfml_sessionEnd.cfm
Labels: testcase

#1775 Added a testcase to thread and tag-islands after the thread statement for LDEV-4157
  test/tickets/LDEV4157.cfc
  test/tickets/LDEV4157/LDEV4157.cfm
  test/tickets/LDEV4157/test4157.cfc
Labels: testcase

#1773 Added a testcase Chaining method on returned object from returned UDF for LDEV-4160
  test/tickets/LDEV4160.cfc
  test/tickets/LDEV4160/LDEV4160.cfm
Labels: testcase

#1821 Added a testcase to check getBaseTagList() inside CFModule execution for LDEV-3359
  test/tickets/LDEV3359.cfc
  test/tickets/LDEV3359/LDEV3359.cfm
  test/tickets/LDEV3359/inner.cfm
  test/tickets/LDEV3359/outer.cfm
Labels: testcase

#1820 Added a testcase to check tag islands in cfc function below the static function for LDEV-3184
  test/tickets/LDEV3184.cfc
  test/tickets/LDEV3184/LDEV3184.cfc
Labels: testcase

#1858 Added a to break without a semicolon inside the script for LDEV-4250
  test/tickets/LDEV4250.cfc
Labels: testcase

#1851 Added a testcase to check Hash() with numIterations argument for LDEV-4243
  test/tickets/LDEV4243.cfc
Labels: testcase

#1850 LDEV-2773 test case for unscoped access to thread scope
  test/tickets/LDEV2773.cfc
Labels: testcase

#1844 Added a testcast to applicationStop() with multiple requests for LDEV-3613
  test/tickets/LDEV3613.cfc
  test/tickets/LDEV3613/Application.cfc
  test/tickets/LDEV3613/LDEV3613.cfm
Labels: testcase

#1830 Added a testcase to check the decimal datatype values in cfquery for LDEV-3599
  test/tickets/LDEV3559.cfc
  test/tickets/LDEV3559/Application.cfc
  test/tickets/LDEV3559/LDEV3559.cfm
Labels: testcase

#1824 Added alias "mimetype" for "accept" in fileupload for LDEV-4218 (lucee 6.0)
  core/src/main/java/resource/fld/core-base.fld
Labels: enhancement

#1835 Added a fix to include the debugging data in singleMode for LDEV-3280
  core/src/main/cfml/context/admin/Application.cfc
  core/src/main/cfml/context/admin/debugging.logs.cfm
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#1836 LDEV-4223 return sessionType as cfml, not application
  core/src/main/java/lucee/runtime/listener/AppListenerUtil.java
Labels: bugfix

#1837 LDEV-4223 return sessionType as cfml, not application (5.3)
  core/src/main/java/lucee/runtime/listener/AppListenerUtil.java
Labels: bugfix

#1822 Added a fix to thread debug logging to entry the total time and include thread name for LDEV-4216 & LDEV-4217
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/java/lucee/runtime/PageContextImpl.java
  core/src/main/java/lucee/runtime/debug/DebuggerImpl.java
  core/src/main/java/lucee/runtime/thread/ChildThreadImpl.java
Labels: bugfix

#1852 Added a fix to log the cfhttp connection failures to the trace log for LDEV-4242
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: enhancement

#1853 Added a fix to log the cfhttp connection failures to the trace log for LDEV-4242 (lucee-5.3)
  core/src/main/java/lucee/runtime/tag/Http.java
Labels: enhancement

#1840 Added a fix to cfimap action="listallfolders" for LDEV-4227
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
Labels: bugfix

#1838 Added a fix to cfimap with uid to use UIDFolder interface for LDEV-4147
  .github/workflows/main.yml
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
  core/src/main/java/lucee/runtime/tag/_Mail.java
  core/src/main/java/lucee/runtime/type/util/ListUtil.java
  test/tickets/LDEV4147.cfc
  test/tickets/LDEV4147/sendMails.cfm
Labels: testcase, bugfix

#1849 updated a test to using equal(=) in script syntax component function attribute for LDEV-3963
  test/tickets/LDEV3963.cfc
  test/tickets/LDEV3963/LDEV3963.cfm
  test/tickets/LDEV3963/test3963.cfc
Labels: testcase

#1859 LDEV-4217 LDEV-4216 revert changing code
  core/src/main/java/lucee/runtime/thread/ChildThreadImpl.java
Labels: bugfix

#1727 LDEV-4110 set update provider timeouts to 5000ms rather than -1
  core/src/main/java/lucee/runtime/config/DeployHandler.java
  core/src/main/java/lucee/runtime/net/http/HTTPClient.java
Labels: enhancement

#1772 Added a testcase to check length property value to sqltype=varchar on ORM Entity for LDEV-4150
  test/tickets/LDEV4150.cfc
  test/tickets/LDEV4150/Application.cfc
  test/tickets/LDEV4150/LDEV4150.cfm
  test/tickets/LDEV4150/test4150.cfc
Labels: testcase

#1765 Added a testcase to checking the multiple queries with nested errors in MSSQL for LDEV-4140
  test/tickets/LDEV4140.cfc
Labels: testcase

#1766 Added a testcase to compound concatenation operator(&=) in finally with local scope prefix for LDEV-4151
  test/tickets/LDEV4151.cfc
Labels: testcase

#1756 Added a testcase to check unzip a file from s3 bucket to s3 bucket for LDEV-3196
  test/tickets/LDEV3196.cfc
Labels: testcase

#1737 LDEV-3265 remove old sun jndi jars
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement, shrink, build

#1739 LDEV-4120 remove old stax and css2 jars
  core/pom.xml
  loader/pom.xml
Labels: shrink, build

#1506 Added a tests to check the member function in some dateTime functions
  test/functions/DateCompare.cfc
  test/functions/DateDiff.cfc
  test/functions/DayOfYear.cfc
  test/functions/DaysInMonth.cfc
  test/functions/DaysInYear.cfc
Labels: testcase

#1856 Added a fix to support strict argument in fileUpload()/fileUploadAll() for LDEV-4232
  core/src/main/java/lucee/runtime/functions/file/FileUpload.java
  core/src/main/java/lucee/runtime/functions/file/FileUploadAll.java
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix

#1731 LDEV-4028 imap fixes
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
Labels: bugfix

#1402 don't append / to the front of a windows path
  core/src/main/java/lucee/commons/io/res/util/ResourceUtil.java
Labels: bugfix

#1771 Added a testcase to new java(class)/new component(cfcPath) syntax for LDEV-4156
  test/tickets/LDEV4156.cfc
Labels: testcase

#1808 Added a testcase to InternalRequest public function for LDEV-4200
  test/functions/InternalRequest.cfc
Labels: testcase

#1514 Bug fix:mail server to use application defined mail servers first for LDEV-3088
  core/src/main/java/lucee/runtime/net/mail/ServerImpl.java
Labels: bugfix

#1828 Added a fix to include charset, failTo, replyTo in mail listener arguments for LDEV-4219
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
  core/src/main/java/lucee/runtime/spooler/CFMLSpoolerTaskListener.java
  core/src/main/java/lucee/runtime/spooler/mail/MailSpoolerTask.java
  core/src/main/java/resource/tld/core-base.tld
Labels: enhancement

#1659 Added a fix to show datasource name in query dump result for LDEV-3070
  core/src/main/java/lucee/runtime/type/QueryImpl.java
  core/src/main/java/lucee/runtime/type/query/QueryArray.java
  core/src/main/java/lucee/runtime/type/query/QueryStruct.java
  core/src/main/java/lucee/runtime/type/util/QueryUtil.java
  test/tickets/LDEV3070.cfc
  test/tickets/LDEV3070/Application.cfc
  test/tickets/LDEV3070/LDEV3070.cfm
Labels: testcase, bugfix

#1583 Add failing test for getMetadata on UDFs
  test/functions/GetMetaData.cfc
Labels: testcase

#1860 LDEV-4252 list failed tests on github action run summary page
  test/run-tests.cfm
Labels: build

#1861 Corrected the casting of config to configWebPro instead of configImpl for LDEV-4216 & LDEV-4217
  core/src/main/java/lucee/runtime/thread/ChildThreadImpl.java
  test/tickets/LDEV3689.cfc
Labels: testcase, bugfix
