Repository lucee/Lucee, pull requests merged in 2022-05, with the labels that each got.

#1632 Added a testcase to writing logs in files using cflog for LDEV-3978
  test/tickets/LDEV3978.cfc
  test/tickets/LDEV3978/LDEV3978.cfm
Labels: testcase

#1612 Added a cache clear button in Admin-services-cache edit page For LDEV-3936
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/server.logging.create.cfm
  core/src/main/cfml/context/admin/services.cache.create.cfm
  core/src/main/java/resource/context/admin/resources/language/en.xml
Labels: enhancement

#1639 LDEV-3754 add cfmail debug=true (5.3)
  core/src/main/cfml/context/admin/services.mail.cfm
  core/src/main/java/lucee/runtime/net/mail/SMTPVerifier.java
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
  core/src/main/java/lucee/runtime/tag/Mail.java
  core/src/main/java/resource/tld/core-base.tld
  test/tickets/LDEV3754.cfc
Labels: enhancement, testcase

#1531 LDEV-0417 include maxrows in query cache signature
  core/src/main/java/lucee/runtime/cache/tag/CacheHandlerCollectionImpl.java
  core/src/main/java/lucee/runtime/tag/Query.java
  core/src/main/java/lucee/runtime/tag/StoredProc.java
  core/src/main/java/resource/tld/core-base.tld
  test/tickets/LDEV0417.cfc
Labels: testcase, bugfix

#1178 cfldap timeout LDEV-1860
  core/src/main/java/lucee/runtime/net/ldap/LDAPClient.java
  core/src/main/java/lucee/runtime/tag/Ldap.java
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix

#1572 Added a fix for new HTTP().send() method to work with url argument for LDEV-2468
  core/src/main/java/resource/component/org/lucee/cfml/Http.cfc
Labels: bugfix

#1072 Add CFSCHEDULE userAgent LDEV-2999
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/services.schedule.edit.cfm
  core/src/main/java/lucee/runtime/schedule/ExecutionThread.java
  core/src/main/java/lucee/runtime/schedule/ScheduleTaskImpl.java
  core/src/main/java/lucee/runtime/schedule/ScheduleTaskPro.java
  core/src/main/java/lucee/runtime/schedule/SchedulerImpl.java
  core/src/main/java/lucee/runtime/tag/Admin.java
  core/src/main/java/lucee/runtime/tag/Schedule.java
  core/src/main/java/resource/tld/core-base.tld
  loader/src/main/java/lucee/runtime/schedule/ScheduleTask.java
Labels: enhancement

#1647 add update provider GHA
  .github/workflows/update-provider.yml
  test/update-provider.cfm
Labels: build

#1649 Added a test for callback argument in QueryColumnData
  test/functions/QueryColumnData.cfc
Labels: testcase

#1653 Added a fix to cfhttp throwOnError to include url and method in error detail for LDEV-4011
  core/src/main/java/lucee/runtime/tag/Http.java
  test/tickets/LDEV4011.cfc
Labels: enhancement, testcase

#1655 LDEV-4012 add support for skip=true for testcases
  ant/run-testcases.xml
Labels: testcase, build
