Repository lucee/Lucee, pull requests merged in 2022-11, with the labels that each got.

#1706 CFMail splitting long HTML lines into multiple lines breaking the HTML [LDEV-4039]
  ant/build-core.xml
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
  core/src/main/java/lucee/runtime/net/smtp/StringDataSource.java
  loader/.settings/org.eclipse.jdt.apt.core.prefs
  test/_setupTestServices.cfc
  test/tags/Mail.cfc
  test/tags/_Mail.cfc
Labels: enhancement, testcase

#1869 include all caused by's from test java stacktraces (disabled)
  test/_testRunner.cfc
Labels: exceptions, build

#1870 LDEV-4261 show java stacktraces in summary
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: build

#1867 Added a fix to graph.cfm throw 404 for invalid query string LDEV-4260
  core/src/main/cfml/context/graph.cfm
Labels: bugfix

#1868 Added a fix to graph.cfm throw 404 for invalid query string LDEV-4260 (5.3)
  core/src/main/cfml/context/graph.cfm
  core/src/main/java/resource/context/graph.cfm
Labels: bugfix

#1865 Added a testcase to sub component for LDEV-4215
  test/general/SubComponent.cfc
  test/general/cfc/index.cfm
Labels: testcase

#1877 LDEV-4205 update EHCache
  core/src/main/java/META-INF/MANIFEST.MF
  loader/build.xml
  loader/pom.xml
Labels: enhancement

#1873 Fix for LDEV-4044 & LDEV-3878 -> 6.0
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/exp/DatabaseException.java
  core/src/main/java/lucee/runtime/exp/IllegalQoQException.java
  core/src/main/java/lucee/runtime/sql/SelectParser.java
  core/src/main/java/lucee/runtime/tag/util/QueryParamConverter.java
  test/tickets/LDEV3878.cfc
  test/tickets/LDEV4044.cfc
Labels: enhancement, bugfix

#1883 LDEV-4282 test case for recompile error after bytecode error
  test/tickets/LDEV4282.cfc
Labels: testcase

#1885 LDEV-4261 backport GHA test summary output (5.4)
  .github/workflows/main.yml
  ant/run-testcases.xml
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: testcase, build

#1884 Added a testcase to imageGetEXIFMetadata()
  test/functions/ImageGetEXIFMetadata.cfc
Labels: testcase
