Repository lucee/Lucee, pull requests merged in 2022-03, with the labels that each got.

#1580 Added a testcase to Custom tag/include page inside a thread for LDEV-3689
  test/tickets/LDEV3689.cfc
  test/tickets/LDEV3689/LDEV3689.cfm
  test/tickets/LDEV3689/dollar.cfm
  test/tickets/LDEV3689/test.cfm
  test/tickets/LDEV3689/withApp/Application.cfc
  test/tickets/LDEV3689/withApp/LDEV3689.cfm
  test/tickets/LDEV3689/withApp/dollar.cfm
  test/tickets/LDEV3689/withApp/test.cfm
Labels: testcase

#905 sameFormFieldsAsArray does not convert fields to arrays if all inputs are empty LDEV-2795
  core/src/main/java/lucee/runtime/type/scope/ScopeSupport.java
  test/tickets/LDEV2795.cfc
Labels: bugfix

#1581 Added a fix to admin application sorting with 5th version number element for LDEV-3887
  core/src/main/cfml/context/admin/ext.applications.detail.cfm
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#1590 LDEV-3264 add test cases for onSessionEnd
  core/src/main/java/lucee/runtime/tag/Admin.java
  test/tickets/LDEV3264.cfc
  test/tickets/LDEV3264/cfml-session/Application.cfc
  test/tickets/LDEV3264/cfml-session/testOnSessionEnd.cfm
  test/tickets/LDEV3264/j2ee-session/Application.cfc
  test/tickets/LDEV3264/j2ee-session/testOnSessionEnd.cfm
Labels: testcase

#1591 Improved the ORM dialects tests to check if services is available
  test/orm/Hibernate.cfc
Labels: testcase

#1594 Added a testcase to sameFormFieldsAsArray = false for LDEV-3909
  test/tickets/LDEV2795.cfc
Labels: testcase

#1602 LDEV-1619 enabled test cases
  test/tickets/LDEV1619.cfc
  test/tickets/LDEV2795.cfc
  test/tickets/_LDEV1619.cfc
Labels: testcase

#1595 Added a testcase to check cfstoredproc exception in MSSQL using raiseError() for LDEV-3908
  test/tickets/LDEV3908.cfc
  test/tickets/LDEV3908/Application.cfc
  test/tickets/LDEV3908/LDEV3908.cfm
Labels: testcase

#1601 add sameFormFieldsAsArray to tag definition
  core/src/main/java/resource/tld/core-cfml.tld
Labels: documentation

#1592 Modified the PDF orientation tests API for LDEV-3868
  test/tags/PDF.cfc
Labels: testcase
