Repository lucee/Lucee, pull requests merged in 2023-07, with the labels that each got.

#2145 add es.json, update de.json translations, change identation to tab and
  core/src/main/cfml/context/admin/resources/language/de.json
  core/src/main/cfml/context/admin/resources/language/es.json
Labels: enhancement

#2149 LDEV-4594 support $ in names for qoq table and column names
  core/src/main/java/lucee/runtime/sql/SelectParser.java
  test/tickets/LDEV4593.cfc
Labels: testcase, bugfix

#2156 LDEV-4603 testcase parser gets stuck in endless loop with huge cfs file
  test/tickets/LDEV4603.cfc
Labels: testcase

#1650 Added a fix: dateTime member functions to work with dateTime formatted string for LDEV-3384
  core/src/main/java/lucee/runtime/type/util/MemberUtil.java
  test/tickets/LDEV3384.cfc
Labels: testcase, bugfix

#2158 LDEV-4606 unbundle hibernate from default distribution
  ant/build-core.xml
  ant/build-extensions.xml
  core/src/main/java/META-INF/MANIFEST.MF
Labels: build

#2137 Added a fix to wrap the mapping physical path inside a container for LDEV-4496
  core/src/main/cfml/context/admin/server.export.cfm
Labels: bugfix

#2155 LDEV-4602 test case for stack overflow with large cfml file
  test/tickets/LDEV4602.cfc
Labels: testcase

#2154 LDEV-4601 test case for cfinclude paths
  test/tickets/LDEV4601.cfc
Labels: testcase

#2153 LDEV-2127 test case for bytecode mem usage
  test/tickets/LDEV2127.cfc
Labels: testcase

#2135 Updated a title & description in lucee admin event gateway page for LDEV-4574
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/java/resource/context/admin/resources/language/en.xml
  test/components/Administrator/en.xml
Labels: enhancement

#1929 Added a testcase to check cfparam with random Attribute for LDEV-4366
  test/tickets/LDEV4366.cfc
Labels: testcase

#2159 LDEV-4558 lucee zero, also build lucee light as part of the build
  ant/upload-to-s3.xml
  ant/upload_to_s3.cfm
Labels: build

#2162 LDEV-4609 unbundle hibernate ext from 5.4.1 onwards
  ant/build-core.xml
  core/src/main/java/META-INF/MANIFEST.MF
Labels: shrink, build

#2164 LDEV-4592 LDEV-4613 qoq fix for incompatible data type in operation
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4592.cfc
  test/tickets/LDEV4613.cfc
Labels: testcase, bugfix

#2165 LDEV-4615 QoQ: treat char as varchar
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4615.cfc
Labels: testcase, bugfix

#2166 LDEV-4615 QoQ: treat char as varchar (6.0)
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4615.cfc
Labels: testcase, bugfix

#2167 Admin overview page update notification re-enabled
  core/src/main/cfml/context/admin/overview.cfm
Labels: bugfix

#2163 LDEV-4610 Add requestExclusive param to administrator.updateDatasource()
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
Labels: bugfix

#2161 Added a fix to catch the debugging templates error in admin and always get the duplicate result of debug data for LDEV-4087 (6.0)
  core/src/main/cfml/context/admin/debugging.logs.detail.cfm
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#2160 Added a fix to catch the debugging templates error in admin and always get the duplicate result of debug data for LDEV-4087 (5.4)
  core/src/main/cfml/context/admin/debugging.logs.detail.cfm
  core/src/main/cfml/context/admin/debugging.logs.list.cfm
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#2173 LDEV-4632 update tests test to use s3 bucket prefix 6.0
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/extension/S3.cfc
  test/functions/S3functions.cfc
  test/functions/StoreACL.cfc
  test/functions/StoreMetaData.cfc
  test/general/Resources.cfc
  test/general/S3.cfc
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV1129.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
  test/tickets/LDEV3196.cfc
  test/tickets/LDEV4407/index.cfm
  test/tickets/_LDEV1348.cfc
  test/tickets/_LDEV1774.cfc
Labels: testcase, build

#2172 LDEV-4632 update tests test to use s3 bucket prefix 5.4
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/extension/S3.cfc
  test/functions/StoreMetaData.cfc
  test/general/Resources.cfc
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV1129.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
  test/tickets/LDEV2410.cfc
  test/tickets/LDEV4407/index.cfm
  test/tickets/_LDEV1774.cfc
Labels: testcase, build

#2174 Added a fix to admin overview page update notification for LDEV-4631
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#2175 LDEV-4178 DirectoryCreate allow any storageLocation (passthru) 6.0
  core/src/main/java/lucee/runtime/tag/Directory.java
  core/src/main/java/lucee/runtime/tag/FileTag.java
  test/functions/StoreGetMetaData.cfc
  test/tickets/LDEV4178.cfc
  test/tickets/LDEV4635.cfc
Labels: enhancement, testcase, bugfix

#2176 LDEV-4640 handle missing xml update provider entry, also auto update to https
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
Labels: bugfix

#2177 LDEV-4640 handle missing update entry, also auto update to https
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
Labels: bugfix

#2182 backport test cleanup from 5.4
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/_testRunner.cfc
  test/cache/Memcached.cfc
  test/cache/MemcachedV3.cfc
  test/datasource/H2.cfc
  test/datasource/HSQLDB.cfc
  test/datasource/JDBCDrivers.cfc
  test/extension/S3.cfc
  test/functions/StoreMetaData.cfc
  test/general/CacheHandler.cfc
  test/general/Resources.cfc
  test/jira/Jira2049/Application.cfc
  test/jira/Jira2733.cfc
  test/jira/Jira3053.cfc
  test/jira/Jira3077.cfc
  test/jira/Jira3087.cfc
  test/orm/Hibernate.cfc
  test/orm/many2many/Application.cfc
  test/run-tests.cfm
  test/tags/Http.cfc
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV0931.cfc
  test/tickets/LDEV1129.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
  test/tickets/LDEV1489/Application.cfc
  test/tickets/LDEV1489/test.cfm
  test/tickets/LDEV2410.cfc
  test/tickets/_LDEV1774.cfc
Labels: testcase, build

#2181 LDEV-3451 disable XXE by default
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  core/src/main/java/lucee/runtime/text/xml/XMLUtil.java
  test/tickets/LDEV1676.cfc
  test/tickets/LDEV1676/Application.cfc
  test/tickets/LDEV1676/LDEV1676.cfm
  test/tickets/LDEV4348.cfc
  test/tickets/LDEV4348/Application.cfc
  test/tickets/LDEV4348/LDEV4348.cfm
Labels: enhancement, testcase

#2180 Fix spelling and grammar in Lucee admin
  core/src/main/cfml/context/admin/chartProcess.cfm
  core/src/main/cfml/context/admin/overview.cfm
  core/src/main/cfml/context/admin/resources/language/de.json
  core/src/main/cfml/context/admin/resources/language/en.json
  core/src/main/cfml/context/admin/server.request.cfm
  core/src/main/cfml/context/admin/server.security.cfm
  core/src/main/cfml/context/admin/update.cfm
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
  test/components/Administrator/en.xml
Labels: enhancement

#2183 LDEV-3451 add back support for pass thru of additional xml feature settings
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  core/src/main/java/lucee/runtime/text/xml/XMLUtil.java
  test/tickets/LDEV4348.cfc
  test/tickets/LDEV4348/Application.cfc
Labels: enhancement

#2185 LDEV-4644 only show admin updates for the current major version
  core/src/main/cfml/context/admin/services.update.cfm
  core/src/main/cfml/context/admin/services.update.functions.cfm
  core/src/main/cfml/context/admin/update.cfm
Labels: enhancement

#2186 LDEV-4645 bugfix for cfprocparam and empty char strings
  core/src/main/java/lucee/runtime/tag/ProcParamBean.java
  test/tickets/LDEV1917.cfc
  test/tickets/LDEV1917/Application.cfc
  test/tickets/LDEV1917/test.cfm
Labels: testcase, bugfix

#2187 LDEV-4645 bugfix for cfprocparam and empty char strings (5.4)
  core/src/main/java/lucee/runtime/tag/ProcParamBean.java
  test/tickets/LDEV1917.cfc
  test/tickets/LDEV1917/Application.cfc
  test/tickets/LDEV1917/test.cfm
Labels: testcase, bugfix

#2189 LDEV-4278 fixed lsweek unit tests to check java version
  test/functions/lsWeek.cfc
Labels: testcase, bugfix

#2191 cleanup old tests and update build
  .github/workflows/main.yml
  ant/build-core.xml
  ant/upload-to-s3.xml
  ant/upload_to_s3.cfm
  test/_setupTestServices.cfc
  test/extension/S3.cfc
  test/general/Resources.cfc
  test/tags/Http.cfc
  test/tags/_index2/CFfilex0/file-1aso33gx0znmk_1_spell/_0.cfs
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV0637.cfc
  test/tickets/LDEV0860.cfc
  test/tickets/LDEV0902.cfc
  test/tickets/LDEV0931.cfc
  test/tickets/LDEV1116.cfc
  test/tickets/LDEV1129.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
  test/tickets/LDEV3103.cfc
Labels: testcase, build

#2190 cleanup old tests and build
  .github/workflows/main.yml
  ant/build-core.xml
  ant/upload-to-s3.xml
  ant/upload_to_s3.cfm
  test/_setupTestServices.cfc
  test/extension/S3.cfc
  test/general/Resources.cfc
  test/tags/Http.cfc
  test/tickets/LDEV0359.cfc
  test/tickets/LDEV0931.cfc
  test/tickets/LDEV1116.cfc
  test/tickets/LDEV1129.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1396.cfc
  test/tickets/LDEV1489.cfc
Labels: testcase, build

#2192 cleanup old test and build
  .github/workflows/main.yml
  .vscode/settings.json
  ant/build-core.xml
  ant/run-testcases.xml
  ant/upload-to-s3.xml
  ant/upload_to_s3.cfm
  test/_setupTestServices.cfc
  test/datasource/MySQL.cfc
  test/datasource/PostgreSQL.cfc
  test/jira/Jira2049.cfc
  test/jira/Jira2049/Application.cfc
  test/jira/Jira2903.cfc
  test/jira/Jira3043.cfc
  test/jira/Jira3074.cfc
  test/jira/Jira3157.cfc
  test/tags/Execute.cfc
  test/tags/Http.cfc
  test/tickets/LDEV0078.cfc
  test/tickets/LDEV0078/Application.cfc
  test/tickets/LDEV0233.cfc
  test/tickets/LDEV0233/Application.cfc
  test/tickets/LDEV0563.cfc
  test/tickets/LDEV0563/mysql/Application.cfc
  test/tickets/LDEV0826.cfc
  test/tickets/LDEV0931.cfc
  test/tickets/LDEV1176.cfc
  test/tickets/LDEV1229.cfc
  test/tickets/LDEV1229/Application.cfc
  test/tickets/LDEV1292.cfc
  test/tickets/LDEV1292/test1/Application.cfc
  test/tickets/LDEV1292/test2/Application.cfc
  test/tickets/LDEV1576.cfc
  test/tickets/LDEV1576/Application.cfc
  test/tickets/LDEV1661.cfc
  test/tickets/LDEV1661/Application.cfc
  test/tickets/LDEV1793.cfc
  test/tickets/LDEV1793/Application.cfc
  test/tickets/LDEV1980.cfc
  test/tickets/LDEV2266.cfc
  test/tickets/LDEV2586.cfc
Labels: testcase, build

#2193 Added a testcase for listQualifiedToArray()
  test/functions/listQualifiedToArray.cfc
Labels: testcase

#2195 Added a testcase for xmlNew() function
  test/functions/xmlNew.cfc
Labels: testcase

#2194 LDEV-4651 additional test cases for xxe doctypeDisallow
  test/tickets/LDEV4651.cfc
  test/tickets/LDEV4651/Application.cfc
  test/tickets/LDEV4651/LDEV4651.cfm
Labels: testcase

#2196 LDEV-3110 xmlParse, isXml support for xmlFeature directives
  core/src/main/java/lucee/runtime/functions/decision/IsXML.java
  core/src/main/java/lucee/runtime/functions/xml/XmlParse.java
  core/src/main/java/lucee/runtime/text/xml/XMLUtil.java
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV3110.cfc
Labels: enhancement, testcase
