Repository lucee/Lucee, pull requests merged in 2023-02, with the labels that each got.

#1950 Pull hardcoded text to lang resource files, fix translations
  core/src/main/cfml/context/admin/resources/language/de.xml
  core/src/main/cfml/context/admin/resources/language/en.xml
  core/src/main/cfml/context/admin/server.compiler.cfm
Labels: enhancement

#1953 Enabled the tests for query with commented line - LDEV-4394
  test/tickets/LDEV1740.cfc
  test/tickets/LDEV1740/Application.cfc
  test/tickets/LDEV2754.cfc
Labels: testcase

#1954 Enabled the tests for query with commented line - LDEV-4394 (5.4)
  test/tickets/LDEV1740.cfc
  test/tickets/LDEV1740/Application.cfc
  test/tickets/LDEV2754.cfc
  test/tickets/_LDEV1740.cfc
Labels: testcase

#1955 Enabled the tests for query with commented line - LDEV-4394 (5.3)
  test/tickets/LDEV1740.cfc
  test/tickets/LDEV1740/Application.cfc
  test/tickets/LDEV2754.cfc
  test/tickets/_LDEV1740.cfc
Labels: testcase

#1958 Improve tests and fix spelling
  loader/src/main/java/lucee/runtime/db/DataSource.java
  test/tickets/LDEV3167.cfc
  test/tickets/LDEV3335.cfc
  test/tickets/LDEV3734.cfc
  test/tickets/LDEV3736.cfc
  test/tickets/LDEV4044.cfc
  test/tickets/LDEV4121.cfc
  test/tickets/_LDEV1484.cfc
  test/tickets/_LDEV1539.cfc
Labels: documentation, testcase

#1959 Add Spanish Translation to the Lucee Administrator es.xml
  core/src/main/cfml/context/admin/resources/language/es.xml
Labels: enhancement

#1948 Added a fix to verify the cache connection before check the cache count for LDEV-4390
  core/src/main/cfml/context/admin/services.cache.create.cfm
Labels: bugfix

#1961 LDEV-4395 testcase for transaction rollback behavior with savepoints
  test/tickets/LDEV4395.cfc
Labels: testcase

#1956 Added a fix to schedule task page is blank in single mode for LDEV-3347
  core/src/main/cfml/context/admin/index.cfm
  core/src/main/cfml/context/admin/server.cfm
  core/src/main/cfml/context/admin/services.schedule.cfm
Labels: bugfix

#1964 build: improve java stack trace filtering
  test/_testRunner.cfc
Labels: build

#1965 Added a fix to make cfpop work correctly with port attribute for LDEV-4401 (lucee 5.3)
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
Labels: bugfix

#1969 LDEV-4408 testcase for sessions with redis and application action=update
  ant/build-core.xml
  test/tickets/LDEV4408.cfc
  test/tickets/LDEV4408/Application.cfc
  test/tickets/LDEV4408/index.cfm
Labels: testcase
