Repository lucee/Lucee, pull requests merged in 2023-06, with the labels that each got.

#2096 LDEV-1526 hsqldb 2.7.2 (5.4)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
  loader/pom.xml
  test/_setupTestServices.cfc
  test/datasource/HSQLDB.cfc
Labels: enhancement

#2097 Added a fix to correctly update the default cache connection in the lucee admin UI for LDEV-4342
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
Labels: bugfix

#2095 LDEV-4510 add bufferOutput and supressContent to getApplicationSettings
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  test/functions/getApplicationSettings.cfc
Labels: enhancement

#2094 LDEV-4503 avoid crash when datasource password is null
  core/src/main/cfml/context/admin/services.datasource.create.cfm
  core/src/main/cfml/context/admin/services.datasource.list.cfm
Labels: enhancement, bugfix

#2099 LDEV-2418 add lucee.pagePool.maxSize env var
  core/src/main/java/lucee/runtime/PageSourcePool.java
Labels: enhancement

#2100 add build test services to 5.4 build (imap,pop3,ldap,redis.memcached)
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/cache/Memcached.cfc
  test/tickets/LDEV4408.cfc
  test/tickets/LDEV4408/Application.cfc
  test/tickets/LDEV4408/index.cfm
Labels: testcase, build

#2024 Added a testcase to checking positional/named arguments on ORM EntityLoadByPk() For LDEV-4461
  test/tickets/LDEV4461.cfc
  test/tickets/LDEV4461/Application.cfc
  test/tickets/LDEV4461/LDEV4461.cfm
  test/tickets/LDEV4461/test4461.cfc
Labels: testcase

#2106 Added a fix to deleting the cache via Admin cache page for LDEV-4522
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#2104 LDEV-4461 fix for EntityLoadByPk with named args
  core/src/main/java/lucee/runtime/functions/orm/EntityLoadByPK.java
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV4461.cfc
  test/tickets/LDEV4461/LDEV4461.cfm
Labels: testcase, bugfix

#2108 LDEV-4466 update memcached to 4.0.0.9 (5.4)
  test/_setupTestServices.cfc
  test/cache/Memcached.cfc
Labels: enhancement

#2109 LDEV-4466 update memcached to 4.0.0.9 (6.0)
  test/_setupTestServices.cfc
  test/cache/Memcached.cfc
Labels: enhancement

#2111 LDEV-4526 fail build on service error LUCEE_BUILD_FAIL_CONFIGURED_SERVICES_FATAL (6.0)
  .github/workflows/main.yml
  test/_setupTestServices.cfc
Labels: build

#2110 LDEV-4526 fail build on service error LUCEE_BUILD_FAIL_CONFIGURED_SERVICES_FATAL (5.4)
  .github/workflows/main.yml
  test/_setupTestServices.cfc
Labels: build

#2112 LDEV-4339 test case for closing orm sessions
  test/tickets/LDEV4339.cfc
  test/tickets/LDEV4339/Application.cfc
  test/tickets/LDEV4339/Entity.cfc
  test/tickets/LDEV4339/ormSessionCheck.cfm
Labels: testcase

#2113 update mssql ext to 12.2.0.jre8
  core/src/main/java/META-INF/MANIFEST.MF
  test/_setupTestServices.cfc
Labels: enhancement

#2114 LDEV-4342 cache create regression test case
  core/src/main/java/lucee/runtime/tag/Admin.java
  test/tickets/LDEV4342.cfc
Labels: exceptions, testcase

#2117 LDEV-4526 build still run tests, but fail afterwards (6.0)
  test/_setupTestServices.cfc
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: build

#2116 LDEV-4526 build still run tests, but fail afterwards (5.4)
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/_testRunner.cfc
  test/run-tests.cfm
Labels: build

#2102 enable orm tests for 5.4 updates
  test/tickets/LDEV4067.cfc
  test/tickets/LDEV4185.cfc
  test/tickets/LDEV4285.cfc
Labels: testcase

#2107 LDEV-3907 update testcase with entitySave force=true
  test/tickets/LDEV3907.cfc
  test/tickets/LDEV3907/LDEV3907.cfm
Labels: testcase

#2084 LDEV-4295 throw meaning exception when datasource config is empty
  core/src/main/java/lucee/runtime/listener/AppListenerUtil.java
  test/tickets/LDEV4295.cfc
Labels: enhancement, exceptions, testcase

#2103 LDEV-4285 fix for named arguments with ORM entityLoad
  core/src/main/java/lucee/runtime/functions/orm/EntityLoad.java
  test/tickets/LDEV4285.cfc
  test/tickets/LDEV4285/test.cfm
Labels: testcase, bugfix

#2083 LDEV-4225 better json parsing error feedback
  core/src/main/java/lucee/runtime/interpreter/CFMLExpressionInterpreter.java
  test/tickets/LDEV4225.cfc
Labels: enhancement, exceptions, testcase

#2067 LDEV-3340 Don't store empty session/client scope to storage by default
  core/src/main/java/lucee/runtime/type/scope/storage/IKHandlerCache.java
  core/src/main/java/lucee/runtime/type/scope/storage/IKHandlerDatasource.java
Labels: enhancement

#2066 LDEV-1718 default to lucee mappings first
  core/src/main/java/lucee/runtime/config/ConfigServerFactory.java
  test/tickets/LDEV1718.cfc
Labels: enhancement, testcase

#1994 Added a testcase to Check decodeFromURL() for LDEV-4437
  test/tickets/LDEV4437.cfc
Labels: testcase

#2121 LDEV-4539 - admin show memory usage on overview page
  core/src/main/cfml/context/admin/chartProcess.cfm
  core/src/main/cfml/context/admin/overview.cfm
Labels: enhancement

#1927 LDEV-4358 fix resource leak opening db connections
  core/src/main/java/lucee/runtime/db/DCStack.java
  core/src/main/java/lucee/runtime/db/DatasourceConnectionPool.java
Labels: bugfix

#2125 Added a testcase to check precisionEvaluate() function for LDEV-4545
  test/tickets/LDEV4545.cfc
Labels: testcase

#2129 Added a testcase to check query() for LDEV-4555 (lucee 5.4)
  test/tickets/LDEV4555.cfc
Labels: testcase

#1755 Added a testcase to check the large number value in query with cfqueryparam for LDEV-4137
  test/tickets/LDEV4137.cfc
  test/tickets/LDEV4137/Application.cfc
  test/tickets/LDEV4137/LDEV4137.cfm
Labels: testcase

#2115 Added a fix to add a sessionCookie settings in GetApplicationSettings() for LDEV-4515
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  test/tickets/LDEV2900.cfc
  test/tickets/LDEV2900/session-cookie/Application.cfc
  test/tickets/LDEV2900/session-cookie/index.cfm
Labels: enhancement

#2134 Update text.cfm in the Lucee 6 admin for lang fallback
  core/src/main/cfml/context/admin/resources/text.cfm
Labels: bugfix

#2131 LDEV-4573 build: copy core to temp loader (windows hotfix)
  ant/build-core.xml
Labels: build

#2136 Enhance language resource file loading LDEV-4577
  core/src/main/cfml/context/admin/admin_layout.cfm
  core/src/main/cfml/context/admin/resources/text.cfm
Labels: enhancement

#2138 LDEV-4582 testcase for expandpath on an invalid mapping
  test/tickets/LDEV4582.cfc
  test/tickets/LDEV4582/Application.cfc
  test/tickets/LDEV4582/index.cfm
Labels: testcase

#2139 Added a testcase to check query.columnList.listToArray() for LDEV-4581
  test/tickets/LDEV4581.cfc
Labels: testcase

#2140 LDEV-4588 add built with lucee version into admin
  ant/build-create-archive.xml
  core/src/main/cfml/context/admin/overview.cfm
  core/src/main/cfml/context/admin/version.cfm
Labels: enhancement

#2143 LDEV-4593 support hsqldb with $ in table and column names
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4593.cfc
Labels: testcase, bugfix

#2144 LDEV-4593 support hsqldb with $ in table and column names (5.4)
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4593.cfc
Labels: testcase, bugfix
