Repository lucee/Lucee, pull requests merged in 2023-04, with the labels that each got.

#1997 add missing descriptions
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/fld/core-cfml.fld
Labels: documentation

#1995 Added a fix to correctly throw an error message using invalid component in the event gateway for LDEV-4438
  core/src/main/java/resource/context/admin/gdriver/AsynchronousEvents.cfc
Labels: bugfix

#1996 Added a testcase to check numberFormat() with decimal value for LDEV-4439
  test/tickets/LDEV4439.cfc
Labels: testcase

#1846 Added a fix to blockedExtensions arguments to work on fileUpload()/fileUploadAll() for LDEV-4238
  core/src/main/java/lucee/runtime/functions/file/FileUpload.java
  core/src/main/java/lucee/runtime/functions/file/FileUploadAll.java
Labels: bugfix

#1947 Added a fix to works correctly arrayNew() with type="date" for LDEV-4387
  core/src/main/java/lucee/runtime/type/ArrayTyped.java
  test/functions/Typed_Array.cfc
Labels: testcase, bugfix

#1977 fix NPE on CallStackGet() for LDEV-4416
  core/src/main/java/lucee/runtime/functions/system/CallStackGet.java
Labels: bugfix

#1829 Added a fix to include charset, failTo, replyTo in mail listener arguments for LDEV-4219 (lucee-5.3)
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
  core/src/main/java/lucee/runtime/spooler/CFMLSpoolerTaskListener.java
  core/src/main/java/lucee/runtime/spooler/mail/MailSpoolerTask.java
Labels: enhancement

#1841 Added a fix to query param missing exception to include sql in detail for LDEV-4229
  core/src/main/java/lucee/runtime/tag/util/QueryParamConverter.java
  test/tickets/LDEV4229.cfc
Labels: testcase, bugfix

#1842 Added a fix to query param missing exception to include sql in detail for LDEV-4229 (lucee-5.3)
  core/src/main/java/lucee/runtime/tag/util/QueryParamConverter.java
  test/tickets/LDEV4229.cfc
Labels: testcase, bugfix

#2000 Added variant of datePart argument to docs
  core/src/main/java/lucee/runtime/functions/dateTime/DateDiff.java
  core/src/main/java/resource/fld/core-base.fld
Labels: documentation

#2009 LDEV-4449 test case for preciseMath
  test/tickets/LDEV4449.cfc
  test/tickets/LDEV4449/Application.cfc
  test/tickets/LDEV4449/index.cfm
Labels: testcase

#2008 Updated descriptions of Compress() and Extract()
  core/src/main/java/lucee/runtime/functions/system/Compress.java
  core/src/main/java/lucee/runtime/functions/system/Extract.java
  core/src/main/java/resource/fld/core-base.fld
Labels: documentation

#2006 LDEV-4446 Add rand() function to QoQ
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/db/SQLImpl.java
  test/tickets/LDEV4446.cfc
Labels: enhancement, testcase

#2005 Fix error handling and HSQLDB fallback
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  test/tickets/LDEV4445.cfc
Labels: bugfix

#2007 Added a fix to correctly show the tooltip on lucee admin Bundle (jar) page edit option for LDEV-4447
  core/src/main/cfml/context/res/js/admin.js
Labels: bugfix

#1992 Added a fix to editing the datasource name to work for LDEV-4433
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#2004 Revert the fix Backward incompatibility (ACF incompatibility) for LDEV-4306 (6.0)
  core/src/main/java/lucee/runtime/functions/international/SetLocale.java
Labels: bugfix

#2003 Revert the fix Backward incompatibility (ACF incompatibility) for LDEV-4306 (5.3)
  core/src/main/java/lucee/runtime/functions/international/SetLocale.java
Labels: bugfix

#1998 LDEV-4440 expose mapping listenerType and ListenerMode in admin
  core/src/main/cfml/context/admin/resources.mappings.cfm
  core/src/main/cfml/context/admin/resources.mappings.edit.cfm
  core/src/main/cfml/context/admin/resources.mappings.list.cfm
  core/src/main/cfml/context/admin/resources/language/en.json
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: enhancement

#1978 Fix spelling
  core/src/main/java/lucee/commons/lang/compiler/JavaCCompiler.java
  core/src/main/java/lucee/runtime/config/CFConfigImport.java
  core/src/main/java/lucee/runtime/functions/system/ConfigImport.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/StoreACL.cfc
  test/general/Resources.cfc
  test/general/S3.cfc
  test/tickets/LDEV0860.cfc
  test/tickets/LDEV1292.cfc
  test/tickets/LDEV1576.cfc
  test/tickets/LDEV1661.cfc
  test/tickets/LDEV1980.cfc
  test/tickets/LDEV3207/Application.cfc
  test/tickets/LDEV3358/Application.cfc
Labels: documentation, exceptions

#2010 docs(README): fix button to link to the contributors list
  README.md
Labels: documentation

#1970 LDEV-4408 testcase for sessions with redis and application action=update (5.3)
  .github/workflows/main.yml
  test/_setupTestServices.cfc
  test/tickets/LDEV4408.cfc
  test/tickets/LDEV4408/Application.cfc
  test/tickets/LDEV4408/index.cfm
Labels: testcase

#1989 Added a fix for switching admin mode to prevents the web password merged to server config for LDEV-4418
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1907 LDEV-4279 update all commons libs (6.0)
  ant/build-core.xml
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  core/src/main/java/lucee/commons/io/res/type/smb/SMBResource.java
  core/src/main/java/lucee/runtime/net/http/MultiPartResponseUtils.java
  core/src/main/java/lucee/runtime/net/smtp/StringDataSource.java
  loader/pom.xml
  test/tickets/LDEV4155.cfc
Labels: enhancement

#2012 LDEV-3869 upgrade commons-compress to 1.23.0
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#2013 Added a fix to redirect correctly when click the upgrade notification from the overview page
  core/src/main/cfml/context/admin/update.cfm
Labels: bugfix

#2016 Added a testcase for ImageInfo()
  test/functions/ImageInfo.cfc
Labels: testcase

#2011 Added a test to check Nested try/finally block for LDEV-4451
  test/tickets/LDEV3393.cfc
  test/tickets/LDEV3393/nestedFinallyBlock.cfm
Labels: testcase

#1990 Added a fix to Archives & Resources - CFX tags for LDEV-4431
  core/src/main/cfml/context/admin/resources.cfx_tags.cfm
Labels: bugfix

#1987 Added a fix to works correctly cfheader/cfparam tag with end tag for LDEV-4428
  core/src/main/java/resource/tld/core-base.tld
  core/src/main/java/resource/tld/core-cfml.tld
Labels: bugfix

#2019 Added a testcase to urlEncode() & binaryEncode() functions
  test/functions/BinaryEncode.cfc
  test/functions/URLEncode.cfc
Labels: testcase

#1848 Added a fix to make this.blockedextforfileupload work with the file uploads for LDEV-4237 (5.3)
  core/src/main/java/lucee/runtime/tag/FileTag.java
Labels: bugfix

#1847 Added a fix to make this.blockedextforfileupload work with the file uploads for LDEV-4237
  core/src/main/java/lucee/runtime/tag/FileTag.java
Labels: bugfix

#2021 Added a testcase for FileInfo function
  test/functions/FileInfo.cfc
Labels: testcase

#2022 Added a testcase to check Imageshear() with shear argument for LDEV-4459
  test/tickets/LDEV4459.cfc
Labels: testcase

#2023 Added a testcase to check imageAddBorder() with negative value of thickness argument for LDEV-4460
  test/tickets/LDEV4460.cfc
Labels: testcase
