Repository lucee/Lucee, pull requests merged in 2023-12, with the labels that each got.

#2280 Added a fix to the mailserver on application tag for LDEV-1868
  core/src/main/java/resource/tld/core-cfml.tld
Labels: bugfix

#2269 Added a testcase in Admin-getApplicationListener() for LDEV-4717
  test/tickets/LDEV4717.cfc
Labels: testcase

#2203 LDEV-4664 update jsch to 0.2.11
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#2228 LDEV-4688 RestError handling and subresource locator
  core/src/main/java/lucee/runtime/ComponentPageImpl.java
Labels: enhancement

#2222 Added a proxy settings in GetApplicationSettings() for LDEV-4569
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
Labels: enhancement

#2045 LDEV-4479 remove jta lib (java 2 support)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: shrink

#1309 LDEV-4441 don't deploy admin when not enabled
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
Labels: enhancement
