Repository lucee/Lucee, pull requests merged in 2023-05, with the labels that each got.

#2025 Added a testcase for structKeyTranslate() & structUpdate functions
  test/functions/StructKeyTranslate.cfc
  test/functions/StructUpdate.cfc
Labels: testcase

#2027 Enabled the test for SubComponent
  test/general/SubComponent.cfc
Labels: testcase

#2026 Added a testcase for query functions
  test/functions/QueryColumnCount.cfc
  test/functions/QueryColumnList.cfc
  test/functions/QueryEvery.cfc
  test/functions/QuerySetCell.cfc
  test/functions/QuerySlice.cfc
  test/functions/QuerySome.cfc
Labels: testcase

#2030 Added a testcase for queryCurrentRow & queryGetCell functions
  test/functions/QueryCurrentRow.cfc
  test/functions/QueryGetCell.cfc
Labels: testcase

#2031 build: report if any tests as skipped in a suite
  test/_testRunner.cfc
Labels: build

#938 cfdump hide and show doesn't work with query LDEV-2865
  core/src/main/java/lucee/runtime/type/util/QueryUtil.java
Labels: bugfix

#1305 Implement getMetaData in QueryImpl for LDEV-2855
  core/src/main/java/lucee/runtime/type/QueryImpl.java
Labels: enhancement

#1348 add line number to cftimer debug logs LDEV-3401
  core/src/main/java/lucee/runtime/debug/DebugTimerImpl.java
  core/src/main/java/lucee/runtime/debug/DebugTimerPro.java
  core/src/main/java/lucee/runtime/debug/DebuggerImpl.java
  core/src/main/java/lucee/runtime/debug/DebuggerPro.java
  core/src/main/java/lucee/runtime/tag/Timer.java
  core/src/main/java/resource/context/admin/debug/Modern.cfc
Labels: enhancement

#1946 LDEV-4386 update to jna 5.13.0
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#1973 LDEV-4410 stop queryparam casting empty strings to nulls
  core/src/main/java/lucee/runtime/db/SQLCaster.java
  test/tickets/LDEV1532.cfc
Labels: enhancement, testcase

#1380 Changed the admin-Overview page webroot and config-File to shows as text
  core/src/main/cfml/context/admin/overview.cfm
Labels: enhancement

#1509 Added a fix for Administrator.Updatedatasource() to support liveTimeout in LDEV-3803
  core/src/main/java/resource/component/org/lucee/cfml/Administrator.cfc
  test/tickets/LDEV3803.cfc
Labels: enhancement, testcase

#2032 Added a testcase for fix() function
  test/functions/Fix.cfc
Labels: testcase

#2033 Added a testcase for fileSetLastModified,findOneOf,reReplace,rTrim & replaceNoCase functions
  test/functions/FileSetLastModified.cfc
  test/functions/FindOneOf.cfc
  test/functions/REReplace.cfc
  test/functions/RTrim.cfc
  test/functions/ReplaceNoCase.cfc
Labels: testcase

#2034 Added a testcase to check cfwddx with action=cfml2wddx for LDEV-3573
  test/functions/rereplacenocase.cfc
  test/tickets/LDEV3573.cfc
Labels: testcase

#1952 Added a testcase to checking cfwddx tag with empty data for LDEV-4392
  test/LDEV4392.cfc
Labels: testcase

#1957 Added a testcase to checking directoryList() UDF filter arguments for LDEV-4393
  core/src/main/java/lucee/commons/io/res/util/UDFFilter.java
  test/tickets/LDEV4393.cfc
Labels: testcase

#1924 LDEV-4353 trim resource extension paths to 255 characters
  core/src/main/java/lucee/commons/io/res/util/ResourceUtil.java
Labels: exceptions

#1784 LDEV-4175 cfhttp add error key to result
  core/src/main/java/lucee/runtime/tag/Http.java
  core/src/main/java/resource/tld/core-base.tld
  test/tags/Http.cfc
Labels: enhancement, testcase

#2035 LDEV-4392 handle empty wddx deserialization like acf
  core/src/main/java/lucee/runtime/converter/WDDXConverter.java
  test/LDEV4392.cfc
Labels: testcase, bugfix

#1909 LDEV-4332 fileWriteLine uses wrong line separator on windows
  core/src/main/java/lucee/runtime/functions/file/FileWriteLine.java
  test/functions/FileReadLine.cfc
  test/functions/FileWriteLine.cfc
Labels: testcase, bugfix

#1622 Added a fix to listAppend()/prepend() with includeEmptyFields and empty string as list/delimiter for LDEV-3949 & LDEV-3956
  core/src/main/java/lucee/runtime/functions/list/ListAppend.java
  core/src/main/java/lucee/runtime/functions/list/ListPrepend.java
  test/tickets/LDEV3949.cfc
Labels: testcase, bugfix

#2042 Added a testcase for functions
  test/functions/Cfusion_decrypt.cfc
  test/functions/HTMLCodeFormat.cfc
  test/functions/IsQuery.cfc
  test/functions/IsWddx.cfc
  test/functions/Rand.cfc
  test/functions/RandRange.cfc
  test/functions/SetVariable.cfc
Labels: testcase

#2043 Added a testcase to check left() for LDEV-4475
  test/tickets/LDEV4475.cfc
Labels: testcase

#2046 Added a testcase For isBinary(), isPDFObject(), isStruct() & isXML() functions
  test/functions/IsBinary.cfc
  test/functions/IsPDFObject.cfc
  test/functions/IsStruct.cfc
  test/functions/IsXml.cfc
Labels: testcase

#1533 LDEV-1526 update hsqldb to 2.7.0 (QoQ)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  loader/pom.xml
  test/_setupTestServices.cfc
  test/datasource/HSQLDB.cfc
  test/datasource/JDBCDrivers.cfc
  test/general/CacheHandler.cfc
  test/jira/Jira2733.cfc
  test/jira/Jira3049/Application.cfc
  test/jira/Jira3053.cfc
  test/jira/Jira3077.cfc
  test/jira/Jira3087.cfc
Labels: enhancement, build

#2041 LDEV-4392 ignore whitespace and comments in wddx
  core/src/main/java/lucee/runtime/converter/WDDXConverter.java
  test/LDEV4392.cfc
Labels: testcase, bugfix

#2052 updated a test to checking directoryList() UDF filter arguments for LDEV-4393
  test/tickets/LDEV4393.cfc
Labels: testcase

#2053 Added a testcase for generate3DESKey(), generatePBKDFkey() & firstDayOfMonth() functions
  test/functions/FirstDayOfMonth.cfc
  test/functions/Generate3DESKey.cfc
  test/functions/GeneratePBKDFkey.cfc
Labels: testcase

#2055 Added a fix to wrap cache connection custom data inside a container for LDEV-4486
  core/src/main/cfml/context/admin/server.export.cfm
Labels: bugfix

#2054 LDEV-4485 configImport needs to understand datasource allowed_select etc
  core/src/main/java/lucee/runtime/tag/CFConfigImport.java
  test/tickets/LDEV4485.cfc
Labels: enhancement, testcase

#2058 Added a testcase to check toNumeric() & trimWhiteSpace() functions
  test/functions/ToNumeric.cfc
  test/functions/TrimWhitespace.cfc
Labels: testcase

#2057 Added a fix to copy the admin code on the export page to the clipboard for LDEV-4489
  core/src/main/cfml/context/admin/admin_layout.cfm
Labels: bugfix

#2060 LDEV-4469 test case for static final error with changed include in cfc
  test/tickets/LDEV4469.cfc
  test/tickets/LDEV4469/Application.cfc
  test/tickets/LDEV4469/Base.cfc
  test/tickets/LDEV4469/C.cfc
  test/tickets/LDEV4469/include.cfm
  test/tickets/LDEV4469/include2.cfm
  test/tickets/LDEV4469/index.cfm
Labels: testcase

#2044 LDEV-4120 remove old stax and css2 jars (take 2)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: shrink, build

#2062 LDEV-4477 remove xmpcore from lucee core (5.4)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: shrink

#2063 LDEV-1526 update hsqldb to 2.7.0 - QoQ (5.4)
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
  loader/pom.xml
  test/_setupTestServices.cfc
  test/datasource/HSQLDB.cfc
  test/datasource/JDBCDrivers.cfc
  test/general/CacheHandler.cfc
  test/jira/Jira2733.cfc
  test/jira/Jira3049/Application.cfc
  test/jira/Jira3053.cfc
  test/jira/Jira3077.cfc
  test/jira/Jira3087.cfc
Labels: enhancement

#2064 LDEV-3820 build use nashorn for java 17 support
  ant/build-bundles.xml
  ant/build-core.xml
  ant/build-create-archive.xml
  ant/build-extensions.xml
  ant/build-test-stable-loader.xml
  ant/build-utils.xml
  ant/build-warmup-test.xml
  ant/lib/asm-9.5.jar
  ant/lib/asm-commons-9.5.jar
  ant/lib/asm-tree-9.5.jar
  ant/lib/asm-util-9.5.jar
  ant/lib/maven-ant-tasks-2.1.3.jar
  ant/lib/nashorn-core-15.4.jar
  ant/run-testcases.xml
  ant/upload-to-s3.xml
  loader/build.xml
  loader/pom.xml
Labels: build

#1871 improved the creating an index on cf_session_data fails exception to includes the original error in caused by LDEV-4248
  core/src/main/java/lucee/runtime/type/scope/storage/db/Ansi92.java
Labels: enhancement

#2070 LDEV-4493 add support for cfmail priority
  core/src/main/java/lucee/runtime/net/smtp/SMTPClient.java
  core/src/main/java/lucee/runtime/tag/Mail.java
  core/src/main/java/resource/tld/core-base.tld
  test/tickets/LDEV4493.cfc
  test/tickets/LDEV4493/priority.cfm
Labels: enhancement, testcase

#2071 Added a fix to wrap the mapping physical path inside a container for LDEV-4496
  core/src/main/cfml/context/admin/resources.mappings.edit.cfm
  core/src/main/cfml/context/admin/server.export.cfm
  core/src/main/cfml/context/res/css/admin6.css
Labels: enhancement

#2069 Added a testcase for isImage(), isInstanceOf() & isLeapYear() functions
  test/functions/IsImage.cfc
  test/functions/IsInstanceOf.cfc
  test/functions/IsLeapYear.cfc
Labels: testcase

#2068 Added a testcase to collection functions
  test/functions/CollectionEach.cfc
  test/functions/CollectionEvery.cfc
  test/functions/CollectionFilter.cfc
  test/functions/CollectionSome.cfc
  test/functions/collectionMap.cfc
  test/functions/collectionReduce.cfc
Labels: testcase

#2073 merge missing tests cases into 6.0
  test/tickets/IsWithinTransaction.cfc
  test/tickets/LDEV1188.cfc
  test/tickets/LDEV1188/bad.json
  test/tickets/LDEV1188/bad2.json
  test/tickets/LDEV1188/god.json
  test/tickets/LDEV1188/schema.json
  test/tickets/LDEV1445.cfc
  test/tickets/LDEV1880.cfc
  test/tickets/LDEV2410.cfc
  test/tickets/LDEV3410.cfc
  test/tickets/LDEV3847.cfc
  test/tickets/LDEV3883.cfc
  test/tickets/LDEV3883/Application.cfc
  test/tickets/LDEV3883/LDEV3883.cfm
  test/tickets/LDEV3883/eventHandler.cfc
  test/tickets/LDEV3883/person.cfc
  test/tickets/LDEV3883/test.cfc
  test/tickets/LDEV3912.cfc
  test/tickets/LDEV3912/app1/sub/importCFC.cfc
  test/tickets/LDEV3912/app1/testApp1.cfc
  test/tickets/LDEV3912/app2/sub/importCFC.cfc
  test/tickets/LDEV3912/app2/testApp2.cfc
  test/tickets/LDEV3914.cfc
  test/tickets/LDEV3914/test.cfm
  test/tickets/LDEV3931.cfc
  test/tickets/LDEV3951.cfc
  test/tickets/LDEV3951/LDEV3951.cfm
  test/tickets/LDEV3964.cfc
  test/tickets/LDEV3978.cfc
  test/tickets/LDEV3978/LDEV3978.cfm
  test/tickets/LDEV3980.cfc
  test/tickets/LDEV3980/Application.cfc
  test/tickets/LDEV3980/LDEV3980.cfm
  test/tickets/LDEV3980/person.cfc
  test/tickets/LDEV3992.cfc
  test/tickets/LDEV3992/LDEV3992.cfm
  test/tickets/LDEV4011.cfc
  test/tickets/LDEV4029.cfc
  test/tickets/LDEV4101.cfc
  test/tickets/LDEV4103.cfc
  test/tickets/LDEV4181.cfc
  test/tickets/LDEV4188.cfc
  test/tickets/LDEV4199.cfc
  test/tickets/LDEV4199/LDEV4199.cfm
  test/tickets/LDEV4485.cfc
Labels: testcase

#2072 Added a testcase to getFunctionData() and getTagData() functions
  test/functions/GetFunctionData.cfc
  test/functions/GetTagData.cfc
Labels: testcase

#2002 LDEV-4442 support IMAP flags for cfimap getHeaderOnly/getAll
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
Labels: enhancement

#2075 LDEV-4442 add testcases for cfimap flags
  core/src/main/java/lucee/runtime/net/mail/MailClient.java
  test/tags/Imap.cfc
  test/tickets/LDEV0910.cfc
  test/tickets/LDEV4147.cfc
Labels: testcase

#2077 Added a fix to correctly update the default cache connection in the lucee 5.3 admin for LDEV-4342
  core/src/main/java/lucee/runtime/config/XMLConfigAdmin.java
Labels: bugfix

#2078 Added a fix to correctly update the default cache connection in the lucee 6 admin for LDEV-4342
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
Labels: bugfix

#1810 Added a fix to support the charset attribute in cfhttp for LDEV-1856
  core/src/main/java/lucee/runtime/tag/Http.java
  test/tickets/LDEV1856.cfc
  test/tickets/LDEV1856/myfile.cfm
  test/tickets/LDEV1856/test.cfm
  test/tickets/_LDEV1856.cfc
Labels: testcase, bugfix

#1801 Added a fix to the cffile action=upload attemptedserverfile key returns the name initially attempts to save for LDEV-4201
  core/src/main/java/lucee/runtime/tag/FileTag.java
Labels: bugfix

#1779 Added a fix to Admin - Application detail Page to show the extension category once for LDEV-4171
  core/src/main/cfml/context/admin/ext.applications.detail.cfm
Labels: bugfix

#1966 Added a fix to prevents to show error message multi-time for LDEV-4402
  core/src/main/cfml/context/admin/services.certificates.cfm
Labels: bugfix

#2080 Added a fix to update correctly the default cache connection under the key "cache" in cfconfig.json file for LDEV-4342
  core/src/main/java/lucee/runtime/config/ConfigAdmin.java
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
Labels: bugfix

#2081 LDEV-3765 fix structReplace
  core/src/main/java/lucee/commons/lang/StringUtil.java
  test/tickets/LDEV3765.cfc
Labels: testcase, bugfix

#2082 LDEV-3448 change session cookie defaults to be httpOnly and sameSite lax
  core/src/main/java/lucee/runtime/listener/SessionCookieDataImpl.java
  test/tickets/LDEV3448.cfc
  test/tickets/LDEV3448/session-cfml/Application.cfc
  test/tickets/LDEV3448/session-jee/Application.cfc
Labels: enhancement, testcase

#2079 Added a testcase to Checking callback on structFind() for LDEV-4495
  test/tickets/LDEV4495.cfc
  test/tickets/LDEV4495/test.cfm
Labels: testcase

#2087 Added a testcase to Hash40() and getNumericDate() functions
  test/functions/GetNumericDate.cfc
  test/functions/Hash40.cfc
Labels: testcase

#2089 LDEV-4507 testcase, timeout in function meta data causes bytecode error
  test/tickets/LDEV4507.cfc
  test/tickets/LDEV4507/Application.cfc
  test/tickets/LDEV4507/test4507.cfc
  test/tickets/LDEV4507/test4507simple.cfc
Labels: testcase

#2091 cleanup test
  test/tags/Http.cfc
Labels: testcase

#2092 LDEV-4508 build: allow using custom update provider for tests
  test/_setupTestServices.cfc
  test/tags/Execute.cfc
  test/tags/Http.cfc
  test/tickets/LDEV0931.cfc
  test/tickets/LDEV0973.cfc
  test/tickets/LDEV1020.cfc
  test/tickets/LDEV3847.cfc
  test/tickets/LDEV4011.cfc
  test/tickets/_LDEV0153.cfc
Labels: testcase, build
