Repository lucee/Lucee, pull requests merged in 2023-01, with the labels that each got.

#1925 Add german debug text for LDEV-2871
  core/src/main/cfml/context/admin/resources/language/de.xml
Labels: documentation

#1926 LDEV-3728 test case for cfhttp redirect locations
  test/tickets/LDEV3728.cfc
Labels: testcase

#1935 Added missing argument descriptions
  core/src/main/java/resource/fld/core-base.fld
  core/src/main/java/resource/fld/core-cfml.fld
Labels: documentation

#1933 Added a testcase to Extract the String using array notation with range For LDEV-4374
  test/tickets/LDEV4374.cfc
  test/tickets/LDEV4374/LDEV4374.cfm
Labels: testcase

#1932 Added a testcase to Extract the string using the array notation with negative index For LDEV-4373
  test/tickets/LDEV4373.cfc
Labels: testcase

#1940 LDEV-4379 try and parse just test component headers
  test/_testRunner.cfc
Labels: testcase, build

#1941 LDEV-4381 admin: add lock to avoid concurrency error adding column
  core/src/main/cfml/context/admin/ext.functions.cfm
Labels: bugfix

#1939 Added a testcase to check the typed Array syntax for LDEV-4370
  test/tickets/LDEV4370.cfc
  test/tickets/LDEV4370/LDEV4370.cfm
Labels: testcase

#1937 Added a testcase to check arrayNew() with type argument LDEV-4371
  test/tickets/LDEV4371.cfc
Labels: testcase

#1936 updated a test to Array Slice Implementation for LDEV-1813
  test/tickets/LDEV1813.cfc
  test/tickets/_LDEV1813.cfc
Labels: testcase

#1887 LDEV-4298 QoQ performance enhancements
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  core/src/main/java/lucee/runtime/db/LikeCompareJRE.java
  core/src/main/java/lucee/runtime/db/QoQ.java
  core/src/main/java/lucee/runtime/functions/query/QueryAddRow.java
  core/src/main/java/lucee/runtime/sql/QueryPartitions.java
  core/src/main/java/lucee/runtime/sql/SelectParser.java
  core/src/main/java/lucee/runtime/sql/exp/ColumnExpression.java
  core/src/main/java/lucee/runtime/sql/exp/Expression.java
  core/src/main/java/lucee/runtime/sql/exp/ExpressionSupport.java
  core/src/main/java/lucee/runtime/sql/exp/op/Operation1.java
  core/src/main/java/lucee/runtime/sql/exp/op/Operation2.java
  core/src/main/java/lucee/runtime/sql/exp/op/Operation3.java
  core/src/main/java/lucee/runtime/sql/exp/op/OperationN.java
  core/src/main/java/lucee/runtime/type/DebugQueryColumn.java
  core/src/main/java/lucee/runtime/type/QueryColumnImpl.java
  core/src/main/java/lucee/runtime/type/QueryImpl.java
  core/src/main/java/lucee/runtime/type/comparator/NumberComparator.java
  core/src/main/java/lucee/runtime/type/comparator/QueryComparator.java
  loader/src/main/java/lucee/runtime/db/SQL.java
  test/tickets/LDEV3514.cfc
  test/tickets/LDEV3878.cfc
  test/tickets/LDEV4298.cfc
Labels: enhancement, testcase

#1943 Updated the typed array testcase as per current behaviours
  test/functions/Typed_Array.cfc
  test/tickets/LDEV4371.cfc
Labels: testcase

#1944 LDEV-112 structSort add path alias pathToSubElement (acf-compat)
  core/src/main/java/resource/fld/core-base.fld
  test/functions/structsort.cfc
Labels: enhancement
