Repository lucee/Lucee, pull requests merged in 2023-09, with the labels that each got.

#2224 Added a testcase to checking tag-island in condition loop for LDEV-4685
  test/tickets/LDEV4685.cfc
  test/tickets/LDEV4685/LDEV4685.cfm
Labels: testcase

#2220 Added a testcase for IsUserInRole() function
  test/functions/IsUserInRole.cfc
Labels: testcase

#2219 Added a testcase for fileSeek() function
  test/functions/FileSeek.cfc
Labels: testcase

#2217 Added a testcase for getUserRoles() function
  test/functions/GetUserRoles.cfc
Labels: testcase

#2216 Added a testcase for monthAsString() function
  test/functions/monthAsString.cfc
Labels: testcase

#2215 Added a testcase for monthShortAsString() functions
  test/functions/MonthShortAsString.cfc
Labels: testcase

#2212 Added a testcase for LDEV-4668
  test/tickets/LDEV4668.cfc
Labels: testcase

#2213 Added a testcase for LDEV-4325
  test/tickets/LDEV4325.cfc
Labels: testcase

#2214 Added a testcase to check SerializeJSON() with CFC instance for LDEV-4676
  test/tickets/LDEV-4676.cfc
Labels: testcase

#2229 LDEV-4691 qoq / hsqldb use sql.enforce_strict_size=false; 6.0
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  test/tickets/LDEV4181.cfc
  test/tickets/LDEV4691.cfc
Labels: testcase, bugfix

#2230 LDEV-4691 qoq / hsqldb use sql.enforce_strict_size=false; 5.4
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
  test/tickets/LDEV4181.cfc
  test/tickets/LDEV4691.cfc
Labels: testcase, bugfix

#2208 LDEV-4633 adding testcase to verify component metadata can be written…
  test/tickets/LDEV4633.cfc
  test/tickets/LDEV4633/Application.cfc
  test/tickets/LDEV4633/EmailMarketing.cfc
  test/tickets/LDEV4633/EmailMarketingBase.cfc
  test/tickets/LDEV4633/_BaseBean.cfc
  test/tickets/LDEV4633/_mixin.cfm
Labels: testcase

#2225 LDEV-4686 remove non existant function definitions 6.0
  core/src/main/java/resource/fld/core-lucee.fld
Labels: documentation, bugfix

#2226 LDEV-4686 remove non existant function definitions 5.4
  core/src/main/java/resource/fld/core-lucee.fld
Labels: documentation, bugfix

#2236 LDEV-4695 QoQ HSQLDB enable sql.enforce_types=false (5.4)
  core/src/main/java/lucee/runtime/config/XMLConfigWebFactory.java
  test/tickets/LDEV4695.cfc
Labels: testcase, bugfix

#2235 LDEV-4695 QoQ HSQLDB enable sql.enforce_types=false
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  test/tickets/LDEV4695.cfc
Labels: testcase, bugfix

#2237 LDEV-4699 update commons-compress to 1.24.0
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: bugfix

#2240 LDEV-4704 add dbinfo filter type validation
  core/src/main/java/lucee/runtime/tag/DBInfo.java
  core/src/main/java/resource/tld/core-base.tld
  test/tags/dbInfo.cfc
Labels: enhancement, testcase

#2242 Testcase for Argon2CheckHash() function
  test/functions/Argon2CheckHash.cfc
Labels: testcase

#2241 Testcase for toScript() function
  test/functions/toScript.cfc
Labels: testcase

#2250 LDEV-389 improve testcase, enable passing tests
  test/tickets/LDEV0389.cfc
  test/tickets/_LDEV0389.cfc
Labels: testcase

#2251 LDEV-1868 fix cfapplication mailservers (5.4)
  core/src/main/java/lucee/runtime/tag/Application.java
  test/tickets/LDEV1868.cfc
  test/tickets/_LDEV1868.cfc
Labels: testcase, bugfix
