Repository lucee/Lucee, pull requests merged in 2024-04, with the labels that each got.

#2344 Added a test-case in db-type query with like operator for LDEV-4829
  test/tickets/LDEV4829.cfc
Labels: testcase

#2346 LDEV-4830 test case for mssql, checking that IDENTITYCOL is returned
  test/tickets/LDEV4830.cfc
Labels: testcase

#2349 LDEV-3893 bugfix for queryparam with arrays and list=false via params
  core/src/main/java/lucee/runtime/tag/util/QueryParamConverter.java
  test/tickets/LDEV3893.cfc
Labels: testcase, bugfix

#2350 LDEV-4836 cfhttp add QUERY method support
  core/src/main/java/lucee/runtime/functions/system/InternalRequest.java
  core/src/main/java/lucee/runtime/tag/Http.java
  test/tags/Http.cfc
Labels: enhancement, testcase

#2329 LDEV-4814 add searchResults to getApplicationSettings
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  test/functions/getApplicationSettings.cfc
  test/tickets/LDEV2772.cfc
Labels: documentation, testcase, bugfix

#2355 Support java 11 and 17 build again with 6.1
  ant/build-core.xml
  test/functions/Argon2CheckHash.cfc
  test/functions/GenerateArgon2Hash.cfc
Labels: build

#2356 Added preciseMath to getApplicationSettings for LDEV-4843
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
  test/functions/getApplicationSettings.cfc
Labels: testcase

#2351 LDEV-4839 update commons-compress to 1.26.1
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#2336 Updated the testcase for LDEV-4774
  test/tickets/LDEV4774.cfc
Labels: testcase
