Repository lucee/Lucee, pull requests merged in 2024-05, with the labels that each got.

#2331 LDEV-4813 bug fix: admin, don't log user out when filtering extensions
  core/src/main/cfml/context/admin/ext.applications.cfm
  core/src/main/cfml/context/admin/ext.applications.list.cfm
  core/src/main/cfml/context/admin/resources/language/en.json
Labels: enhancement, bugfix

#2325 LDEV-4801 optimize arrayToList
  core/src/main/java/lucee/runtime/functions/list/ArrayToList.java
  test/tickets/LDEV4801.cfc
Labels: enhancement, testcase

#2326 Added a fix in ExpandPath.java for LDEV-4803
  core/src/main/java/lucee/runtime/functions/system/ExpandPath.java
Labels: bugfix

#2337 test case for each with parallel=true, maxthreads=1
  test/tickets/LDEV2824.cfc
Labels: testcase

#1553 Bug Fix: Duplicator.duplicateMap() to checks serializable instance too for LDEV-3805
  core/src/main/java/lucee/runtime/op/Duplicator.java
  test/tickets/LDEV3805.cfc
Labels: bugfix

#2348 LDEV-4833 build: log memory usage with a GC
  test/run-tests.cfm
Labels: build

#2360 enable test case for LDEV-4648
  test/tickets/LDEV4648.cfc
Labels: testcase

#2359 LDEV-4851 reduce overhead of checkFileLocation
  core/src/main/java/lucee/runtime/security/SecurityManagerImpl.java
Labels: enhancement

#2363 LDEV-3906 allow web admin to function when file access mode is set to local
  core/src/main/cfml/context/admin/admin_layout.cfm
  core/src/main/cfml/context/admin/adminfunctions.cfc
  core/src/main/cfml/context/admin/web.cfm
  core/src/main/java/lucee/runtime/config/ConfigWebFactory.java
  core/src/main/java/lucee/runtime/functions/system/GetApplicationSettings.java
Labels: bugfix

#2330 LDEV-4854 use stricter application options for admin (search results, implicit scopes, limit evaluation)
  core/src/main/cfml/context/admin/Application.cfc
Labels: enhancement

#2368 LDEV-4859 test case for create object (5.4)
  test/tickets/LDEV4859.cfc
Labels: testcase

#2369 LDEV-4859 test case for create object (6.0)
  test/tickets/LDEV4859.cfc
Labels: testcase

#2372 LDEV-3947 http resource exists() stricter status code checks v3
  core/src/main/java/lucee/commons/io/res/type/http/HTTPResource.java
  test/tickets/LDEV3947.cfc
Labels: enhancement, testcase

#2371 LDEV-4861 allow multiple methods for rest end points
  core/src/main/java/lucee/runtime/ComponentPageImpl.java
Labels: enhancement

#2370 LDEV-4773 update to jsch 0.2.17
  core/pom.xml
  core/src/main/java/META-INF/MANIFEST.MF
  loader/pom.xml
Labels: enhancement

#2367 LDEV-3317 optimise qoq hsqldb table loading
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
  core/src/main/java/lucee/runtime/db/QoQ.java
  test/tickets/LDEV3311.cfc
Labels: enhancement, testcase

#2374 LDEV-4866 test case for query parse and single char comments (5.4)
  test/tickets/LDEV4866.cfc
Labels: testcase

#2375 LDEV-4867 test case for sql comments being preserved (5.4)
  test/tickets/LDEV4867.cfc
Labels: testcase
