Repository lucee/Lucee, pull requests merged in 2024-02, with the labels that each got.

#2297 Added a testcase to check the xmlsearch with lenient=true for LDEV-4781
  test/tickets/LDEV4781.cfc
Labels: testcase

#2295 Added a testcase in XmlElemNew() function.
  test/XmlElemNew.cfc
Labels: testcase

#2293 Added a testcase in tan() function.
  test/functions/tan.cfc
Labels: testcase

#2292 Test case for non UTF-8 characters in LDEV-4648 ticket.
  test/tickets/LDEV4648.cfc
Labels: testcase

#2290 Added a testcase to check decimalFormat() for LDEV-4776
  test/tickets/LDEV4776.cfc
Labels: testcase

#2289 Added testcase for call a function with cfloop query in LDEV-4771
  test/tickets/LDEV4771.cfc
  test/tickets/LDEV4771/LDEV4771.cfm
Labels: testcase

#2282 Added a testcase in min() function.
  test/functions/minute.cfc
Labels: testcase

#2278 Added a testcase in sin() function
  test/functions/sin.cfc
Labels: testcase

#2276 Added testcase in sgn() function
  test/functions/sgn.cfc
Labels: testcase

#2275 Added testcase in sqr() function
  test/functions/sqr.cfc
Labels: testcase

#2307 Improve invalid datasource name exception for LDEV-4787
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#2300 Added to continue without a semicolon inside the script for LDEV-4268
  test/tickets/LDEV4268.cfc
  test/tickets/LDEV4268/LDEV4268.cfm
Labels: testcase

#2298 Added a fix in returnFormat is missing from getMetaData() for LDEV-4783 (6.0)
  core/src/main/java/lucee/runtime/type/util/ComponentUtil.java
  test/tickets/LDEV4783.cfc
Labels: testcase, bugfix

#2266 Added a testcase in fileDelete() function with empty directory for LDEV-4494
  test/tickets/LDEV4494.cfc
Labels: testcase

#2260 Added a testcase in dot-operator struct with final static for LDEV-4531
  test/tickets/LDEV4531.cfc
  test/tickets/LDEV4531/A.cfc
  test/tickets/LDEV4531/LDEV4531.cfm
Labels: testcase

#2281 Updated the fix for LDEV-4672
  core/src/main/java/lucee/runtime/CFMLFactoryImpl.java
Labels: bugfix

#2202 LDEV-4658 update default java 19+ date formatting tests
  test/functions/TimeFormat.cfc
  test/jira/Jira2587.cfc
  test/tickets/LDEV1025.cfc
Labels: testcase, bugfix

#2246 LDEV-4282 backport bytecode fix from 6
  core/src/main/java/lucee/runtime/PageSourceImpl.java
  test/tickets/LDEV4282.cfc
Labels: testcase, bugfix

#2234 Added a testcase in QoQ IN-operator for LDEV-4695 (5.4)
  test/tickets/LDEV-4695.cfc
Labels: testcase

#2188 Added a testcase to check default=null with cfparam for LDEV-3246
  test/tickets/LDEV3246.cfc
  test/tickets/LDEV3246/index.cfm
Labels: testcase

#2142 LDEV-4582 backport test from 6
  test/tickets/LDEV4582.cfc
  test/tickets/LDEV4582/Application.cfc
  test/tickets/LDEV4582/index.cfm
Labels: testcase

#1988 Added a testcase to check EHCache with "distributed":"automatic" for LDEV-4429
  test/tickets/LDEV4429.cfc
Labels: testcase

#1912 LDEV-4334 application action="update" mappings=mappings fails
  test/_testRunner.cfc
  test/functions/ContractPath.cfc
  test/functions/ExpandPath.cfc
  test/tickets/LDEV4334.cfc
  test/tickets/LDEV4334/index.cfm
Labels: testcase

#1768 Added a fix and testcase to cflog/writeLog() works with empty text for LDEV-174
  core/src/main/java/lucee/runtime/tag/Log.java
  test/tickets/LDEV174.cfc
Labels: testcase, bugfix

#1740 LDEV-2622 testcase for CFLDAP with TLS
  .github/workflows/main.yml
  core/src/main/java/lucee/runtime/tag/Ldap.java
  core/src/main/java/resource/tld/core-base.tld
  test/_setupTestServices.cfc
  test/tickets/LDEV2622.cfc
Labels: testcase

#1662 Changed directory functions testcases to script
  test/functions/DirectoryCopy.cfc
  test/functions/DirectoryDelete.cfc
  test/functions/DirectoryExists.cfc
  test/functions/DirectoryList.cfc
Labels: testcase

#1644 Added a testcase to cfschedule with userAgent attribute for LDEV-2999
  test/tickets/LDEV2999.cfc
  test/tickets/LDEV2999/userAgent.cfm
Labels: testcase

#2283 Added a testcase in createObject() function
  test/functions/createObject.cfc
Labels: testcase

#2233 Added a testcase in QoQ IN-operator for LDEV-4695
  test/tickets/LDEV-4695.cfc
Labels: testcase

#2179 LDEV-4642 test case for inspect once and invalid cfc falling back to cache
  test/run-tests.cfm
  test/tickets/LDEV4642.cfc
  test/tickets/LDEV4642/Application.cfc
  test/tickets/LDEV4642/LDEV4642.cfm
  test/tickets/LDEV4642/test4642.cfc
Labels: testcase

#2210 LDEV-4126 populate cgi.auth_user as cgi.remote_user
  core/src/main/java/lucee/runtime/type/scope/CGIImpl.java
  core/src/main/java/lucee/runtime/type/scope/CGIImplReadOnly.java
Labels: bugfix

#2085 LDEV-3998 improve exception when a java object can't be serialized
  core/src/main/java/lucee/runtime/converter/ScriptConverter.java
  test/tickets/LDEV3998.cfc
Labels: enhancement, exceptions

#1486 fix FormatBaseN() using negative numbers - LDEV-3776
  core/src/main/java/lucee/runtime/functions/displayFormatting/FormatBaseN.java
Labels: exceptions, bugfix

#1413 Added a fix to Bit functions throws an error for large integer input in LDEV-3666
  core/src/main/java/lucee/runtime/functions/math/BitAnd.java
  core/src/main/java/lucee/runtime/functions/math/BitMaskClear.java
  core/src/main/java/lucee/runtime/functions/math/BitMaskRead.java
  core/src/main/java/lucee/runtime/functions/math/BitMaskSet.java
  core/src/main/java/lucee/runtime/functions/math/BitNot.java
  core/src/main/java/lucee/runtime/functions/math/BitOr.java
  core/src/main/java/lucee/runtime/functions/math/BitSHLN.java
  core/src/main/java/lucee/runtime/functions/math/BitSHRN.java
  core/src/main/java/lucee/runtime/functions/math/BitXor.java
Labels: bugfix

#1275 cfftp action="quote" support LDEV-3274
  core/src/main/java/lucee/runtime/net/ftp/AFTPClient.java
  core/src/main/java/lucee/runtime/net/ftp/FTPClientImpl.java
  core/src/main/java/lucee/runtime/net/ftp/FTPConnection.java
  core/src/main/java/lucee/runtime/net/ftp/FTPConnectionImpl.java
  core/src/main/java/lucee/runtime/net/ftp/FTPSClientImpl.java
  core/src/main/java/lucee/runtime/net/ftp/SFTPClientImpl.java
  core/src/main/java/lucee/runtime/tag/Ftp.java
  core/src/main/java/resource/tld/core-base.tld
  test/_setupTestServices.cfc
  test/tags/FTP.cfc
Labels: enhancement

#1444 Added a fix to GetTagData() & GetFunctionData() to remove extra tabs in description for LDEV-1811
  core/src/main/java/lucee/runtime/functions/other/GetFunctionData.java
  core/src/main/java/lucee/runtime/functions/other/GetTagData.java
Labels: bugfix

#1442 LDEV-3675 - feat(getTempFile): add Retry on getTempFile,
  core/src/main/java/lucee/runtime/functions/system/GetTempFile.java
Labels: enhancement

#1534 Added a testcase: Check the runAsync() to pass the application context and scopes for LDEV-3833
  core/src/main/java/lucee/runtime/future/CallableUDF.java
  test/tickets/LDEV3833.cfc
Labels: testcase, bugfix

#2294 LDEV-3478 call onSessionEnd with sessionRotate
  core/src/main/java/lucee/runtime/type/scope/ScopeContext.java
  test/tickets/LDEV3478.cfc
  test/tickets/LDEV3478/Jee_session_rotate/Application.cfc
  test/tickets/LDEV3478/Jee_session_rotate/test_jee_sessionEnd.cfm
  test/tickets/LDEV3478/cfml_session_rotate/Application.cfc
  test/tickets/LDEV3478/cfml_session_rotate/test_cfml_sessionEnd.cfm
  test/tickets/LDEV4166.cfc
  test/tickets/LDEV4166/Jee_session_Invalidate/Application.cfc
  test/tickets/LDEV4166/Jee_session_Invalidate/test_jee_sessionEnd.cfm
  test/tickets/LDEV4166/cfml_session_Invalidate/Application.cfc
  test/tickets/LDEV4166/cfml_session_Invalidate/test_cfml_sessionEnd.cfm
Labels: testcase, bugfix

#2285 LDEV-4670 test case for database session expiry (WIP)
  core/src/main/java/lucee/runtime/type/scope/storage/db/Ansi92.java
  test/tickets/LDEV4670.cfc
  test/tickets/LDEV4670/Application.cfc
  test/tickets/LDEV4670/ldev4670.cfm
Labels: testcase, bugfix

#2209 LDEV-3743 java 11 fix for negative with dollarFormat and LScurrencyFormat
  core/src/main/java/lucee/runtime/functions/international/LSCurrencyFormat.java
  test/functions/DollarFormat.cfc
  test/functions/LSCurrencyFormat.cfc
Labels: testcase, bugfix

#2201 LDEV-2634 add keySize to GenerateRSAKeys()
  core/src/main/java/lucee/commons/digest/RSA.java
  core/src/main/java/lucee/runtime/coder/RSA.java
  core/src/main/java/lucee/runtime/functions/other/GenerateRSAKeys.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/GenerateRSAKeys.cfc
Labels: enhancement, testcase

#2198 LDEV-4655 remove unsupported tag definitions
  core/src/main/java/resource/tld/core-base.tld
  core/src/main/java/resource/tld/core-cfml.tld
Labels: shrink

#2313 LDEV-4794 use stringbuilder for repeatstring
  core/src/main/java/lucee/commons/lang/StringUtil.java
Labels: enhancement
