Repository lucee/Lucee, pull requests merged in 2024-12, with the labels that each got.

#2448 LDEV-3349 fix url encoding when a plus sign is present
  core/src/main/java/lucee/commons/net/HTTPUtil.java
  core/src/main/java/lucee/commons/net/http/httpclient/HTTPEngine4Impl.java
  core/src/main/java/lucee/runtime/functions/other/URLEncode.java
  core/src/main/java/lucee/runtime/functions/other/URLEncodedFormat.java
  core/src/main/java/lucee/runtime/functions/system/InternalRequest.java
  core/src/main/java/lucee/runtime/net/http/HttpUtil.java
  core/src/main/java/lucee/runtime/net/http/ReqRspUtil.java
  core/src/main/java/lucee/runtime/tag/Http.java
  core/src/main/java/lucee/runtime/type/scope/CookieImpl.java
  core/src/main/java/lucee/runtime/type/scope/util/ScopeUtil.java
  core/src/main/java/resource/setting/sysprop-envvar.json
  test/tickets/LDEV0973.cfc
  test/tickets/LDEV3349.cfc
  test/tickets/LDEV3349/ldev3349.cfm
  test/tickets/LDEV3349/test.cfm
Labels: testcase, bugfix

#2450 LDEV-5161 update tests to test both preciseMath true and false
  test/functions/ACos.cfc
  test/functions/ASin.cfc
  test/functions/Atn.cfc
  test/functions/BitAnd.cfc
  test/functions/BitOr.cfc
  test/functions/sin.cfc
  test/tickets/LDEV3661.cfc
Labels: testcase

#2447 LDEV-4772 LDEV-4975 test case for old lex file bytecode
  core/src/main/java/lucee/runtime/functions/other/CreateObject.java
  test/tickets/LDEV4772.cfc
Labels: testcase, bugfix

#2443 LDEV-5163 cache used columns for qoq-hsqldb
  core/src/main/java/lucee/runtime/db/HSQLDBHandler.java
Labels: enhancement

#2444 LDEV-5156 allow configuring the default capacity for local and arguments scopes
  core/src/main/java/lucee/runtime/type/scope/ArgumentImpl.java
  core/src/main/java/lucee/runtime/type/scope/LocalImpl.java
  core/src/main/java/resource/setting/sysprop-envvar.json
  test/tickets/LDEV5156.cfc
Labels: enhancement

#2451 LDEV-5180 update testcases to test with preciseMath enabled and disabled
  test/functions/BitSHLN.cfc
  test/functions/BitSHRN.cfc
  test/functions/BitXor.cfc
Labels: testcase

#2454 LDEV-5173 test cases for add support for epoch and epochms for ParseDateTime
  test/tickets/LDEV5173.cfc
Labels: testcase

#2460 LDEV-5203 optimize checkPrimaryTypes matching
  core/src/main/java/lucee/commons/lang/ClassUtil.java
Labels: enhancement

#2435 LDEV-5146 test case for expand path directory endings
  core/src/main/java/lucee/runtime/functions/system/ExpandPath.java
  test/functions/ExpandPath.cfc
Labels: testcase

#2463 LDEV-5034 include directories with compressTar, set mode
  core/src/main/java/lucee/commons/io/compress/CompressUtil.java
  core/src/main/java/resource/fld/core-base.fld
  test/tickets/LDEV5034.cfc
Labels: testcase, bugfix

#2462 LDEV-5227 use PosixFileAttributes for getMode / setMode
  core/src/main/java/lucee/commons/io/ModeUtil.java
  core/src/main/java/lucee/commons/io/res/type/file/FileResource.java
Labels: enhancement
