Repository lucee/Lucee, pull requests merged in 2024-03, with the labels that each got.

#2333 LDEV-4815 add formUrlAsStruct to admin scopes page
  core/src/main/cfml/context/admin/resources/language/en.json
  core/src/main/cfml/context/admin/server.scope.cfm
Labels: enhancement

#2324 Added alias "actionParam" for "actionParams" in cfftp for LDEV-3274
  core/src/main/java/resource/tld/core-base.tld
Labels: bugfix

#2341 LDEV-4822 add dimensions alias for arrayNew
  core/src/main/java/resource/fld/core-base.fld
  test/functions/ArrayNew.cfc
Labels: testcase, bugfix
