Repository lucee/Lucee, pull requests merged in 2025-07, with the labels that each got.

#2606 Updated the HelperBase.cfc to validate only the current arguments.
  core/src/main/java/resource/component/org/lucee/cfml/HelperBase.cfc
Labels: enhancement

#2605 Added a fix for "updateDefaultSecurityManager" for LDEV-5684.
  core/src/main/cfml/context/admin/security.access.cfm
  core/src/main/java/lucee/runtime/tag/Admin.java
Labels: bugfix

#2608 Updated the admin page for LDEV-5691
  core/src/main/cfml/context/admin/admin_layout.cfm
Labels: bugfix

#2613 Added the logout option in the Admin for LDEV-5695
  core/src/main/cfml/context/admin/admin_layout.cfm
  core/src/main/cfml/context/admin/resources/css/darkmode.css
  core/src/main/cfml/context/res/css/admin.css
  core/src/main/cfml/context/res/img/logout.png
Labels: enhancement

#2619 LDEV-5706 lazy load cgi read only scope structs
  core/src/main/java/lucee/runtime/type/scope/CGIImplReadOnly.java
Labels: enhancement

#2599 LDEV-5660 testcase to check all manifest bundles have osgi mappings (v6)
  core/src/main/java/lucee/runtime/config/s3/BundleProvider.java
  loader/src/main/java/lucee/loader/engine/BundleProvider.java
  test/tickets/LDEV5567/LDEV5660.cfc
Labels: enhancement, testcase

#2627 LDEV-1975 CFCACHE add useQueryString
  core/src/main/java/lucee/runtime/cache/legacy/CacheItem.java
  core/src/main/java/lucee/runtime/cache/legacy/CacheItemCache.java
  core/src/main/java/lucee/runtime/cache/legacy/CacheItemFS.java
  core/src/main/java/lucee/runtime/tag/Cache.java
  core/src/main/java/resource/tld/core-base.tld
  test/tags/cache.cfc
  test/tags/cache/cache_simple.cfm
  test/tags/cache/cache_useQueryString.cfm
  test/tags/cache/cache_whitespace.cfm
  test/tickets/LDEV4151.cfc
Labels: enhancement, testcase
