Repository lucee/Lucee, pull requests merged in 2025-05, with the labels that each got.

#2562 LDEV-5582 fix extension version update notification banner check
  core/src/main/cfml/context/admin/ext.applications.list.cfm
Labels: bugfix

#2564 Added test case for LDEV-5585
  test/tickets/LDEV5585.cfc
Labels: testcase

#2571 LDEV-5604 allow specifying source struct / scope for cfinsert and cfupdate
  core/src/main/java/lucee/runtime/tag/Insert.java
  core/src/main/java/lucee/runtime/tag/Update.java
  core/src/main/java/resource/tld/core-base.tld
  test/tags/Insert.cfc
  test/tags/Update.cfc
Labels: enhancement

#2568 LDEV-4318 add low level ftp and sftp debugging
  core/src/main/java/lucee/runtime/net/ftp/FTPClientImpl.java
  core/src/main/java/lucee/runtime/net/ftp/SFTPClientImpl.java
Labels: enhancement

#2561 LDEV-2917 allow SSLCertificateInstall to update custom cacert file
  core/src/main/java/lucee/runtime/functions/other/SSLCertificateInstall.java
  core/src/main/java/resource/fld/core-base.fld
  test/functions/SSLCertificateInstall.cfc
Labels: enhancement, exceptions, testcase

#2572 LDEV-5603 Bundled error templates do not account for the current state of enablecfoutputonly (instead assuming it's false)
  core/src/main/cfml/context/templates/error/error.cfm
Labels: bugfix

#2577 LDEV-2038 allow interface methods with any to match any return types
  test/tickets/LDEV2038/ldev2038_cfc.cfc
  test/tickets/LDEV2038/ldev2038_struct.cfc
Labels: testcase, bugfix

#2581 LDEV-5633 refactor ReplaceNoCase approach
  core/src/main/java/lucee/commons/lang/StringUtil.java
Labels: enhancement
